<div align="right" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/ExploreAI_logos/Logo blue_dark.png"  style="width:25px" align="right";/>
</div>

# SQL window functions
© ExploreAI Academy

In this exercise, we will test our understanding and application of SQL window functions on a sample SQLite database file for a retail company called Northwind by performing complex calculations and analyses like ranking, running totals, and date differences. Ensure that you have downloaded the database file, Northwind.db.

## Learning objectives

By the end of this train, you should:
- Use the RANK() function to assign a ranking number to each row based on the order specified within the window.
- Use aggregate window functions to calculate running totals. 
- Use the LAG() function to help calculate the difference, in days, between consecutive date readings in our dataset.
- Use aggregate window functions to calculate the moving average.

First, let's load our sample database:

In [1]:
# Load and activate the SQL extension to allow us to execute SQL in a Jupyter notebook.
%load_ext sql

In [2]:
# Load the Northwind database stored in your local machine. 
# Make sure the file is saved in the same folder as this notebook.
%sql sqlite:///Northwind.db

'Connected: @Northwind.db'

Here is a view of all of our tables in the database:

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/Northwind_ERD.png"  style="width:500px";/>
<br>
<br>
    <em>Figure 1: Northwind ERD</em>
</div>

## Exercise

Run the necessary queries that will provide us with the following information. Compare your queries with the solutions at the end of this notebook.

### Exercise 1

Rank all the orders of a specific customer from the most recent to the least recent using window functions. Assume that the customer ID is `'ALFKI'`.

In [10]:
%%sql

select 
	OrderId,
    OrderDate,
    Rank() Over(Order by OrderDate DESC) AS Order_rank
from Orders
where CustomerId = 'ALFKI';

 * sqlite:///Northwind.db
Done.

[(11011, '1998-04-09 00:00:00', 1),
 (10952, '1998-03-16 00:00:00', 2),
 (10835, '1998-01-15 00:00:00', 3),
 (10702, '1997-10-13 00:00:00', 4),
 (10692, '1997-10-03 00:00:00', 5),
 (10643, '1997-08-25 00:00:00', 6)]

### Exercise 2

Calculate a running total of the quantity of orders using window functions.

In [12]:
%%sql

select 
	OrderId,
    SUM(OrderId) Over(partition by OrderId) AS Quantity
from 
	Orders;

 * sqlite:///Northwind.db
Done.

[(10248, 10248),
 (10249, 10249),
 (10250, 10250),
 (10251, 10251),
 (10252, 10252),
 (10253, 10253),
 (10254, 10254),
 (10255, 10255),
 (10256, 10256),
 (10257, 10257),
 (10258, 10258),
 (10259, 10259),
 (10260, 10260),
 (10261, 10261),
 (10262, 10262),
 (10263, 10263),
 (10264, 10264),
 (10265, 10265),
 (10266, 10266),
 (10267, 10267),
 (10268, 10268),
 (10269, 10269),
 (10270, 10270),
 (10271, 10271),
 (10272, 10272),
 (10273, 10273),
 (10274, 10274),
 (10275, 10275),
 (10276, 10276),
 (10277, 10277),
 (10278, 10278),
 (10279, 10279),
 (10280, 10280),
 (10281, 10281),
 (10282, 10282),
 (10283, 10283),
 (10284, 10284),
 (10285, 10285),
 (10286, 10286),
 (10287, 10287),
 (10288, 10288),
 (10289, 10289),
 (10290, 10290),
 (10291, 10291),
 (10292, 10292),
 (10293, 10293),
 (10294, 10294),
 (10295, 10295),
 (10296, 10296),
 (10297, 10297),
 (10298, 10298),
 (10299, 10299),
 (10300, 10300),
 (10301, 10301),
 (10302, 10302),
 (10303, 10303),
 (10304, 10304),
 (10305, 10305),
 (10306, 10306),
 (10307, 10307),
 (10308, 10308),
 (10309, 10309),
 (10310, 10310),
 (10311, 10311),
 (10312, 10312),
 (10313, 10313),
 (10314, 10314),
 (10315, 10315),
 (10316, 10316),
 (10317, 10317),
 (10318, 10318),
 (10319, 10319),
 (10320, 10320),
 (10321, 10321),
 (10322, 10322),
 (10323, 10323),
 (10324, 10324),
 (10325, 10325),
 (10326, 10326),
 (10327, 10327),
 (10328, 10328),
 (10329, 10329),
 (10330, 10330),
 (10331, 10331),
 (10332, 10332),
 (10333, 10333),
 (10334, 10334),
 (10335, 10335),
 (10336, 10336),
 (10337, 10337),
 (10338, 10338),
 (10339, 10339),
 (10340, 10340),
 (10341, 10341),
 (10342, 10342),
 (10343, 10343),
 (10344, 10344),
 (10345, 10345),
 (10346, 10346),
 (10347, 10347),
 (10348, 10348),
 (10349, 10349),
 (10350, 10350),
 (10351, 10351),
 (10352, 10352),
 (10353, 10353),
 (10354, 10354),
 (10355, 10355),
 (10356, 10356),
 (10357, 10357),
 (10358, 10358),
 (10359, 10359),
 (10360, 10360),
 (10361, 10361),
 (10362, 10362),
 (10363, 10363),
 (10364, 10364),
 (10365, 10365),
 (10366, 10366),
 (10367, 10367),
 (10368, 10368),
 (10369, 10369),
 (10370, 10370),
 (10371, 10371),
 (10372, 10372),
 (10373, 10373),
 (10374, 10374),
 (10375, 10375),
 (10376, 10376),
 (10377, 10377),
 (10378, 10378),
 (10379, 10379),
 (10380, 10380),
 (10381, 10381),
 (10382, 10382),
 (10383, 10383),
 (10384, 10384),
 (10385, 10385),
 (10386, 10386),
 (10387, 10387),
 (10388, 10388),
 (10389, 10389),
 (10390, 10390),
 (10391, 10391),
 (10392, 10392),
 (10393, 10393),
 (10394, 10394),
 (10395, 10395),
 (10396, 10396),
 (10397, 10397),
 (10398, 10398),
 (10399, 10399),
 (10400, 10400),
 (10401, 10401),
 (10402, 10402),
 (10403, 10403),
 (10404, 10404),
 (10405, 10405),
 (10406, 10406),
 (10407, 10407),
 (10408, 10408),
 (10409, 10409),
 (10410, 10410),
 (10411, 10411),
 (10412, 10412),
 (10413, 10413),
 (10414, 10414),
 (10415, 10415),
 (10416, 10416),
 (10417, 10417),
 (10418, 10418),
 (10419, 10419),
 (10420, 10420),
 (10421, 10421),
 (10422, 10422),
 (10423, 10423),
 (10424, 10424),
 (10425, 10425),
 (10426, 10426),
 (10427, 10427),
 (10428, 10428),
 (10429, 10429),
 (10430, 10430),
 (10431, 10431),
 (10432, 10432),
 (10433, 10433),
 (10434, 10434),
 (10435, 10435),
 (10436, 10436),
 (10437, 10437),
 (10438, 10438),
 (10439, 10439),
 (10440, 10440),
 (10441, 10441),
 (10442, 10442),
 (10443, 10443),
 (10444, 10444),
 (10445, 10445),
 (10446, 10446),
 (10447, 10447),
 (10448, 10448),
 (10449, 10449),
 (10450, 10450),
 (10451, 10451),
 (10452, 10452),
 (10453, 10453),
 (10454, 10454),
 (10455, 10455),
 (10456, 10456),
 (10457, 10457),
 (10458, 10458),
 (10459, 10459),
 (10460, 10460),
 (10461, 10461),
 (10462, 10462),
 (10463, 10463),
 (10464, 10464),
 (10465, 10465),
 (10466, 10466),
 (10467, 10467),
 (10468, 10468),
 (10469, 10469),
 (10470, 10470),
 (10471, 10471),
 (10472, 10472),
 (10473, 10473),
 (10474, 10474),
 (10475, 10475),
 (10476, 10476),
 (10477, 10477),
 (10478, 10478),
 (10479, 10479),
 (10480, 10480),
 (10481, 10481),
 (10482, 10482),
 (10483, 10483),
 (10484, 10484),
 (10485, 10485),
 (10486, 10486),
 (10487, 10487),
 (10488, 10488),
 (10489, 10489),
 (10490, 10490),
 (10491, 10491),
 (10492, 10492),
 (10493, 10493),
 (10494, 10494),
 (10495, 10495),
 (10496, 10496),
 (10497, 10497),
 (10498, 10498),
 (10499, 10499),
 (10500, 10500),
 (10501, 10501),
 (10502, 10502),
 (10503, 10503),
 (10504, 10504),
 (10505, 10505),
 (10506, 10506),
 (10507, 10507),
 (10508, 10508),
 (10509, 10509),
 (10510, 10510),
 (10511, 10511),
 (10512, 10512),
 (10513, 10513),
 (10514, 10514),
 (10515, 10515),
 (10516, 10516),
 (10517, 10517),
 (10518, 10518),
 (10519, 10519),
 (10520, 10520),
 (10521, 10521),
 (10522, 10522),
 (10523, 10523),
 (10524, 10524),
 (10525, 10525),
 (10526, 10526),
 (10527, 10527),
 (10528, 10528),
 (10529, 10529),
 (10530, 10530),
 (10531, 10531),
 (10532, 10532),
 (10533, 10533),
 (10534, 10534),
 (10535, 10535),
 (10536, 10536),
 (10537, 10537),
 (10538, 10538),
 (10539, 10539),
 (10540, 10540),
 (10541, 10541),
 (10542, 10542),
 (10543, 10543),
 (10544, 10544),
 (10545, 10545),
 (10546, 10546),
 (10547, 10547),
 (10548, 10548),
 (10549, 10549),
 (10550, 10550),
 (10551, 10551),
 (10552, 10552),
 (10553, 10553),
 (10554, 10554),
 (10555, 10555),
 (10556, 10556),
 (10557, 10557),
 (10558, 10558),
 (10559, 10559),
 (10560, 10560),
 (10561, 10561),
 (10562, 10562),
 (10563, 10563),
 (10564, 10564),
 (10565, 10565),
 (10566, 10566),
 (10567, 10567),
 (10568, 10568),
 (10569, 10569),
 (10570, 10570),
 (10571, 10571),
 (10572, 10572),
 (10573, 10573),
 (10574, 10574),
 (10575, 10575),
 (10576, 10576),
 (10577, 10577),
 (10578, 10578),
 (10579, 10579),
 (10580, 10580),
 (10581, 10581),
 (10582, 10582),
 (10583, 10583),
 (10584, 10584),
 (10585, 10585),
 (10586, 10586),
 (10587, 10587),
 (10588, 10588),
 (10589, 10589),
 (10590, 10590),
 (10591, 10591),
 (10592, 10592),
 (10593, 10593),
 (10594, 10594),
 (10595, 10595),
 (10596, 10596),
 (10597, 10597),
 (10598, 10598),
 (10599, 10599),
 (10600, 10600),
 (10601, 10601),
 (10602, 10602),
 (10603, 10603),
 (10604, 10604),
 (10605, 10605),
 (10606, 10606),
 (10607, 10607),
 (10608, 10608),
 (10609, 10609),
 (10610, 10610),
 (10611, 10611),
 (10612, 10612),
 (10613, 10613),
 (10614, 10614),
 (10615, 10615),
 (10616, 10616),
 (10617, 10617),
 (10618, 10618),
 (10619, 10619),
 (10620, 10620),
 (10621, 10621),
 (10622, 10622),
 (10623, 10623),
 (10624, 10624),
 (10625, 10625),
 (10626, 10626),
 (10627, 10627),
 (10628, 10628),
 (10629, 10629),
 (10630, 10630),
 (10631, 10631),
 (10632, 10632),
 (10633, 10633),
 (10634, 10634),
 (10635, 10635),
 (10636, 10636),
 (10637, 10637),
 (10638, 10638),
 (10639, 10639),
 (10640, 10640),
 (10641, 10641),
 (10642, 10642),
 (10643, 10643),
 (10644, 10644),
 (10645, 10645),
 (10646, 10646),
 (10647, 10647),
 (10648, 10648),
 (10649, 10649),
 (10650, 10650),
 (10651, 10651),
 (10652, 10652),
 (10653, 10653),
 (10654, 10654),
 (10655, 10655),
 (10656, 10656),
 (10657, 10657),
 (10658, 10658),
 (10659, 10659),
 (10660, 10660),
 (10661, 10661),
 (10662, 10662),
 (10663, 10663),
 (10664, 10664),
 (10665, 10665),
 (10666, 10666),
 (10667, 10667),
 (10668, 10668),
 (10669, 10669),
 (10670, 10670),
 (10671, 10671),
 (10672, 10672),
 (10673, 10673),
 (10674, 10674),
 (10675, 10675),
 (10676, 10676),
 (10677, 10677),
 (10678, 10678),
 (10679, 10679),
 (10680, 10680),
 (10681, 10681),
 (10682, 10682),
 (10683, 10683),
 (10684, 10684),
 (10685, 10685),
 (10686, 10686),
 (10687, 10687),
 (10688, 10688),
 (10689, 10689),
 (10690, 10690),
 (10691, 10691),
 (10692, 10692),
 (10693, 10693),
 (10694, 10694),
 (10695, 10695),
 (10696, 10696),
 (10697, 10697),
 (10698, 10698),
 (10699, 10699),
 (10700, 10700),
 (10701, 10701),
 (10702, 10702),
 (10703, 10703),
 (10704, 10704),
 (10705, 10705),
 (10706, 10706),
 (10707, 10707),
 (10708, 10708),
 (10709, 10709),
 (10710, 10710),
 (10711, 10711),
 (10712, 10712),
 (10713, 10713),
 (10714, 10714),
 (10715, 10715),
 (10716, 10716),
 (10717, 10717),
 (10718, 10718),
 (10719, 10719),
 (10720, 10720),
 (10721, 10721),
 (10722, 10722),
 (10723, 10723),
 (10724, 10724),
 (10725, 10725),
 (10726, 10726),
 (10727, 10727),
 (10728, 10728),
 (10729, 10729),
 (10730, 10730),
 (10731, 10731),
 (10732, 10732),
 (10733, 10733),
 (10734, 10734),
 (10735, 10735),
 (10736, 10736),
 (10737, 10737),
 (10738, 10738),
 (10739, 10739),
 (10740, 10740),
 (10741, 10741),
 (10742, 10742),
 (10743, 10743),
 (10744, 10744),
 (10745, 10745),
 (10746, 10746),
 (10747, 10747),
 (10748, 10748),
 (10749, 10749),
 (10750, 10750),
 (10751, 10751),
 (10752, 10752),
 (10753, 10753),
 (10754, 10754),
 (10755, 10755),
 (10756, 10756),
 (10757, 10757),
 (10758, 10758),
 (10759, 10759),
 (10760, 10760),
 (10761, 10761),
 (10762, 10762),
 (10763, 10763),
 (10764, 10764),
 (10765, 10765),
 (10766, 10766),
 (10767, 10767),
 (10768, 10768),
 (10769, 10769),
 (10770, 10770),
 (10771, 10771),
 (10772, 10772),
 (10773, 10773),
 (10774, 10774),
 (10775, 10775),
 (10776, 10776),
 (10777, 10777),
 (10778, 10778),
 (10779, 10779),
 (10780, 10780),
 (10781, 10781),
 (10782, 10782),
 (10783, 10783),
 (10784, 10784),
 (10785, 10785),
 (10786, 10786),
 (10787, 10787),
 (10788, 10788),
 (10789, 10789),
 (10790, 10790),
 (10791, 10791),
 (10792, 10792),
 (10793, 10793),
 (10794, 10794),
 (10795, 10795),
 (10796, 10796),
 (10797, 10797),
 (10798, 10798),
 (10799, 10799),
 (10800, 10800),
 (10801, 10801),
 (10802, 10802),
 (10803, 10803),
 (10804, 10804),
 (10805, 10805),
 (10806, 10806),
 (10807, 10807),
 (10808, 10808),
 (10809, 10809),
 (10810, 10810),
 (10811, 10811),
 (10812, 10812),
 (10813, 10813),
 (10814, 10814),
 (10815, 10815),
 (10816, 10816),
 (10817, 10817),
 (10818, 10818),
 (10819, 10819),
 (10820, 10820),
 (10821, 10821),
 (10822, 10822),
 (10823, 10823),
 (10824, 10824),
 (10825, 10825),
 (10826, 10826),
 (10827, 10827),
 (10828, 10828),
 (10829, 10829),
 (10830, 10830),
 (10831, 10831),
 (10832, 10832),
 (10833, 10833),
 (10834, 10834),
 (10835, 10835),
 (10836, 10836),
 (10837, 10837),
 (10838, 10838),
 (10839, 10839),
 (10840, 10840),
 (10841, 10841),
 (10842, 10842),
 (10843, 10843),
 (10844, 10844),
 (10845, 10845),
 (10846, 10846),
 (10847, 10847),
 (10848, 10848),
 (10849, 10849),
 (10850, 10850),
 (10851, 10851),
 (10852, 10852),
 (10853, 10853),
 (10854, 10854),
 (10855, 10855),
 (10856, 10856),
 (10857, 10857),
 (10858, 10858),
 (10859, 10859),
 (10860, 10860),
 (10861, 10861),
 (10862, 10862),
 (10863, 10863),
 (10864, 10864),
 (10865, 10865),
 (10866, 10866),
 (10867, 10867),
 (10868, 10868),
 (10869, 10869),
 (10870, 10870),
 (10871, 10871),
 (10872, 10872),
 (10873, 10873),
 (10874, 10874),
 (10875, 10875),
 (10876, 10876),
 (10877, 10877),
 (10878, 10878),
 (10879, 10879),
 (10880, 10880),
 (10881, 10881),
 (10882, 10882),
 (10883, 10883),
 (10884, 10884),
 (10885, 10885),
 (10886, 10886),
 (10887, 10887),
 (10888, 10888),
 (10889, 10889),
 (10890, 10890),
 (10891, 10891),
 (10892, 10892),
 (10893, 10893),
 (10894, 10894),
 (10895, 10895),
 (10896, 10896),
 (10897, 10897),
 (10898, 10898),
 (10899, 10899),
 (10900, 10900),
 (10901, 10901),
 (10902, 10902),
 (10903, 10903),
 (10904, 10904),
 (10905, 10905),
 (10906, 10906),
 (10907, 10907),
 (10908, 10908),
 (10909, 10909),
 (10910, 10910),
 (10911, 10911),
 (10912, 10912),
 (10913, 10913),
 (10914, 10914),
 (10915, 10915),
 (10916, 10916),
 (10917, 10917),
 (10918, 10918),
 (10919, 10919),
 (10920, 10920),
 (10921, 10921),
 (10922, 10922),
 (10923, 10923),
 (10924, 10924),
 (10925, 10925),
 (10926, 10926),
 (10927, 10927),
 (10928, 10928),
 (10929, 10929),
 (10930, 10930),
 (10931, 10931),
 (10932, 10932),
 (10933, 10933),
 (10934, 10934),
 (10935, 10935),
 (10936, 10936),
 (10937, 10937),
 (10938, 10938),
 (10939, 10939),
 (10940, 10940),
 (10941, 10941),
 (10942, 10942),
 (10943, 10943),
 (10944, 10944),
 (10945, 10945),
 (10946, 10946),
 (10947, 10947),
 (10948, 10948),
 (10949, 10949),
 (10950, 10950),
 (10951, 10951),
 (10952, 10952),
 (10953, 10953),
 (10954, 10954),
 (10955, 10955),
 (10956, 10956),
 (10957, 10957),
 (10958, 10958),
 (10959, 10959),
 (10960, 10960),
 (10961, 10961),
 (10962, 10962),
 (10963, 10963),
 (10964, 10964),
 (10965, 10965),
 (10966, 10966),
 (10967, 10967),
 (10968, 10968),
 (10969, 10969),
 (10970, 10970),
 (10971, 10971),
 (10972, 10972),
 (10973, 10973),
 (10974, 10974),
 (10975, 10975),
 (10976, 10976),
 (10977, 10977),
 (10978, 10978),
 (10979, 10979),
 (10980, 10980),
 (10981, 10981),
 (10982, 10982),
 (10983, 10983),
 (10984, 10984),
 (10985, 10985),
 (10986, 10986),
 (10987, 10987),
 (10988, 10988),
 (10989, 10989),
 (10990, 10990),
 (10991, 10991),
 (10992, 10992),
 (10993, 10993),
 (10994, 10994),
 (10995, 10995),
 (10996, 10996),
 (10997, 10997),
 (10998, 10998),
 (10999, 10999),
 (11000, 11000),
 (11001, 11001),
 (11002, 11002),
 (11003, 11003),
 (11004, 11004),
 (11005, 11005),
 (11006, 11006),
 (11007, 11007),
 (11008, 11008),
 (11009, 11009),
 (11010, 11010),
 (11011, 11011),
 (11012, 11012),
 (11013, 11013),
 (11014, 11014),
 (11015, 11015),
 (11016, 11016),
 (11017, 11017),
 (11018, 11018),
 (11019, 11019),
 (11020, 11020),
 (11021, 11021),
 (11022, 11022),
 (11023, 11023),
 (11024, 11024),
 (11025, 11025),
 (11026, 11026),
 (11027, 11027),
 (11028, 11028),
 (11029, 11029),
 (11030, 11030),
 (11031, 11031),
 (11032, 11032),
 (11033, 11033),
 (11034, 11034),
 (11035, 11035),
 (11036, 11036),
 (11037, 11037),
 (11038, 11038),
 (11039, 11039),
 (11040, 11040),
 (11041, 11041),
 (11042, 11042),
 (11043, 11043),
 (11044, 11044),
 (11045, 11045),
 (11046, 11046),
 (11047, 11047),
 (11048, 11048),
 (11049, 11049),
 (11050, 11050),
 (11051, 11051),
 (11052, 11052),
 (11053, 11053),
 (11054, 11054),
 (11055, 11055),
 (11056, 11056),
 (11057, 11057),
 (11058, 11058),
 (11059, 11059),
 (11060, 11060),
 (11061, 11061),
 (11062, 11062),
 (11063, 11063),
 (11064, 11064),
 (11065, 11065),
 (11066, 11066),
 (11067, 11067),
 (11068, 11068),
 (11069, 11069),
 (11070, 11070),
 (11071, 11071),
 (11072, 11072),
 (11073, 11073),
 (11074, 11074),
 (11075, 11075),
 (11076, 11076),
 (11077, 11077)]

### Exercise 3


Use window functions to find the difference in successive order dates for each customer. **HINT:** The `TIMESTAMPDIFF()` function in MySQL is not available in SQLite. We can use the `julianday()` function to convert the dates to a floating point number and then calculate the difference.

In [21]:
%%sql

select 
	CustomerId,
    OrderDate,
    lag(OrderDate,1) Over(partition by CustomerId 
                       order by OrderDate) AS prevOrderDay,
    julianday(OrderDate) - julianday(lag(OrderDate,1) Over(partition by CustomerId 
                                                        order by OrderDate)) AS diff_Order_Day
from 
	orders;

 * sqlite:///Northwind.db
Done.

[('ALFKI', '1997-08-25 00:00:00', None, None),
 ('ALFKI', '1997-10-03 00:00:00', '1997-08-25 00:00:00', 39.0),
 ('ALFKI', '1997-10-13 00:00:00', '1997-10-03 00:00:00', 10.0),
 ('ALFKI', '1998-01-15 00:00:00', '1997-10-13 00:00:00', 94.0),
 ('ALFKI', '1998-03-16 00:00:00', '1998-01-15 00:00:00', 60.0),
 ('ALFKI', '1998-04-09 00:00:00', '1998-03-16 00:00:00', 24.0),
 ('ANATR', '1996-09-18 00:00:00', None, None),
 ('ANATR', '1997-08-08 00:00:00', '1996-09-18 00:00:00', 324.0),
 ('ANATR', '1997-11-28 00:00:00', '1997-08-08 00:00:00', 112.0),
 ('ANATR', '1998-03-04 00:00:00', '1997-11-28 00:00:00', 96.0),
 ('ANTON', '1996-11-27 00:00:00', None, None),
 ('ANTON', '1997-04-15 00:00:00', '1996-11-27 00:00:00', 139.0),
 ('ANTON', '1997-05-13 00:00:00', '1997-04-15 00:00:00', 28.0),
 ('ANTON', '1997-06-19 00:00:00', '1997-05-13 00:00:00', 37.0),
 ('ANTON', '1997-09-22 00:00:00', '1997-06-19 00:00:00', 95.0),
 ('ANTON', '1997-09-25 00:00:00', '1997-09-22 00:00:00', 3.0),
 ('ANTON', '1998-01-28 00:00:00', '1997-09-25 00:00:00', 125.0),
 ('AROUT', '1996-11-15 00:00:00', None, None),
 ('AROUT', '1996-12-16 00:00:00', '1996-11-15 00:00:00', 31.0),
 ('AROUT', '1997-02-21 00:00:00', '1996-12-16 00:00:00', 67.0),
 ('AROUT', '1997-06-04 00:00:00', '1997-02-21 00:00:00', 103.0),
 ('AROUT', '1997-10-16 00:00:00', '1997-06-04 00:00:00', 134.0),
 ('AROUT', '1997-11-14 00:00:00', '1997-10-16 00:00:00', 29.0),
 ('AROUT', '1997-11-17 00:00:00', '1997-11-14 00:00:00', 3.0),
 ('AROUT', '1997-12-08 00:00:00', '1997-11-17 00:00:00', 21.0),
 ('AROUT', '1997-12-24 00:00:00', '1997-12-08 00:00:00', 16.0),
 ('AROUT', '1998-02-02 00:00:00', '1997-12-24 00:00:00', 40.0),
 ('AROUT', '1998-03-03 00:00:00', '1998-02-02 00:00:00', 29.0),
 ('AROUT', '1998-03-16 00:00:00', '1998-03-03 00:00:00', 13.0),
 ('AROUT', '1998-04-10 00:00:00', '1998-03-16 00:00:00', 25.0),
 ('BERGS', '1996-08-12 00:00:00', None, None),
 ('BERGS', '1996-08-14 00:00:00', '1996-08-12 00:00:00', 2.0),
 ('BERGS', '1996-12-16 00:00:00', '1996-08-14 00:00:00', 124.0),
 ('BERGS', '1997-02-12 00:00:00', '1996-12-16 00:00:00', 58.0),
 ('BERGS', '1997-02-13 00:00:00', '1997-02-12 00:00:00', 1.0),
 ('BERGS', '1997-05-01 00:00:00', '1997-02-13 00:00:00', 77.0),
 ('BERGS', '1997-06-18 00:00:00', '1997-05-01 00:00:00', 48.0),
 ('BERGS', '1997-08-11 00:00:00', '1997-06-18 00:00:00', 54.0),
 ('BERGS', '1997-09-02 00:00:00', '1997-08-11 00:00:00', 22.0),
 ('BERGS', '1997-09-17 00:00:00', '1997-09-02 00:00:00', 15.0),
 ('BERGS', '1997-10-01 00:00:00', '1997-09-17 00:00:00', 14.0),
 ('BERGS', '1997-11-07 00:00:00', '1997-10-01 00:00:00', 37.0),
 ('BERGS', '1997-12-16 00:00:00', '1997-11-07 00:00:00', 39.0),
 ('BERGS', '1998-01-16 00:00:00', '1997-12-16 00:00:00', 31.0),
 ('BERGS', '1998-01-28 00:00:00', '1998-01-16 00:00:00', 12.0),
 ('BERGS', '1998-02-03 00:00:00', '1998-01-28 00:00:00', 6.0),
 ('BERGS', '1998-02-06 00:00:00', '1998-02-03 00:00:00', 3.0),
 ('BERGS', '1998-03-04 00:00:00', '1998-02-06 00:00:00', 26.0),
 ('BLAUS', '1997-04-09 00:00:00', None, None),
 ('BLAUS', '1997-04-17 00:00:00', '1997-04-09 00:00:00', 8.0),
 ('BLAUS', '1997-06-27 00:00:00', '1997-04-17 00:00:00', 71.0),
 ('BLAUS', '1997-07-29 00:00:00', '1997-06-27 00:00:00', 32.0),
 ('BLAUS', '1998-01-27 00:00:00', '1997-07-29 00:00:00', 182.0),
 ('BLAUS', '1998-03-17 00:00:00', '1998-01-27 00:00:00', 49.0),
 ('BLAUS', '1998-04-29 00:00:00', '1998-03-17 00:00:00', 43.0),
 ('BLONP', '1996-07-25 00:00:00', None, None),
 ('BLONP', '1996-09-04 00:00:00', '1996-07-25 00:00:00', 41.0),
 ('BLONP', '1996-11-22 00:00:00', '1996-09-04 00:00:00', 79.0),
 ('BLONP', '1997-02-05 00:00:00', '1996-11-22 00:00:00', 75.0),
 ('BLONP', '1997-02-18 00:00:00', '1997-02-05 00:00:00', 13.0),
 ('BLONP', '1997-06-05 00:00:00', '1997-02-18 00:00:00', 107.0),
 ('BLONP', '1997-06-12 00:00:00', '1997-06-05 00:00:00', 7.0),
 ('BLONP', '1997-06-30 00:00:00', '1997-06-12 00:00:00', 18.0),
 ('BLONP', '1997-08-12 00:00:00', '1997-06-30 00:00:00', 43.0),
 ('BLONP', '1997-09-23 00:00:00', '1997-08-12 00:00:00', 42.0),
 ('BLONP', '1998-01-12 00:00:00', '1997-09-23 00:00:00', 111.0),
 ('BOLID', '1996-10-10 00:00:00', None, None),
 ('BOLID', '1997-12-29 00:00:00', '1996-10-10 00:00:00', 445.0),
 ('BOLID', '1998-03-24 00:00:00', '1997-12-29 00:00:00', 85.0),
 ('BONAP', '1996-10-16 00:00:00', None, None),
 ('BONAP', '1996-10-29 00:00:00', '1996-10-16 00:00:00', 13.0),
 ('BONAP', '1996-11-25 00:00:00', '1996-10-29 00:00:00', 27.0),
 ('BONAP', '1997-03-11 00:00:00', '1996-11-25 00:00:00', 106.0),
 ('BONAP', '1997-04-18 00:00:00', '1997-03-11 00:00:00', 38.0),
 ('BONAP', '1997-05-02 00:00:00', '1997-04-18 00:00:00', 14.0),
 ('BONAP', '1997-09-10 00:00:00', '1997-05-02 00:00:00', 131.0),
 ('BONAP', '1997-10-23 00:00:00', '1997-09-10 00:00:00', 43.0),
 ('BONAP', '1997-11-05 00:00:00', '1997-10-23 00:00:00', 13.0),
 ('BONAP', '1997-11-06 00:00:00', '1997-11-05 00:00:00', 1.0),
 ('BONAP', '1997-11-26 00:00:00', '1997-11-06 00:00:00', 20.0),
 ('BONAP', '1998-01-12 00:00:00', '1997-11-26 00:00:00', 47.0),
 ('BONAP', '1998-02-05 00:00:00', '1998-01-12 00:00:00', 24.0),
 ('BONAP', '1998-02-09 00:00:00', '1998-02-05 00:00:00', 4.0),
 ('BONAP', '1998-03-06 00:00:00', '1998-02-09 00:00:00', 25.0),
 ('BONAP', '1998-03-11 00:00:00', '1998-03-06 00:00:00', 5.0),
 ('BONAP', '1998-05-06 00:00:00', '1998-03-11 00:00:00', 56.0),
 ('BOTTM', '1996-12-20 00:00:00', None, None),
 ('BOTTM', '1997-01-10 00:00:00', '1996-12-20 00:00:00', 21.0),
 ('BOTTM', '1997-01-10 00:00:00', '1997-01-10 00:00:00', 0.0),
 ('BOTTM', '1997-01-30 00:00:00', '1997-01-10 00:00:00', 20.0),
 ('BOTTM', '1997-04-01 00:00:00', '1997-01-30 00:00:00', 61.0),
 ('BOTTM', '1997-11-14 00:00:00', '1997-04-01 00:00:00', 227.0),
 ('BOTTM', '1998-03-02 00:00:00', '1997-11-14 00:00:00', 108.0),
 ('BOTTM', '1998-03-12 00:00:00', '1998-03-02 00:00:00', 10.0),
 ('BOTTM', '1998-03-13 00:00:00', '1998-03-12 00:00:00', 1.0),
 ('BOTTM', '1998-03-25 00:00:00', '1998-03-13 00:00:00', 12.0),
 ('BOTTM', '1998-03-27 00:00:00', '1998-03-25 00:00:00', 2.0),
 ('BOTTM', '1998-04-16 00:00:00', '1998-03-27 00:00:00', 20.0),
 ('BOTTM', '1998-04-23 00:00:00', '1998-04-16 00:00:00', 7.0),
 ('BOTTM', '1998-04-24 00:00:00', '1998-04-23 00:00:00', 1.0),
 ('BSBEV', '1996-08-26 00:00:00', None, None),
 ('BSBEV', '1997-03-11 00:00:00', '1996-08-26 00:00:00', 197.0),
 ('BSBEV', '1997-03-24 00:00:00', '1997-03-11 00:00:00', 13.0),
 ('BSBEV', '1997-05-15 00:00:00', '1997-03-24 00:00:00', 52.0),
 ('BSBEV', '1997-05-16 00:00:00', '1997-05-15 00:00:00', 1.0),
 ('BSBEV', '1997-06-24 00:00:00', '1997-05-16 00:00:00', 39.0),
 ('BSBEV', '1997-07-15 00:00:00', '1997-06-24 00:00:00', 21.0),
 ('BSBEV', '1998-03-11 00:00:00', '1997-07-15 00:00:00', 239.0),
 ('BSBEV', '1998-03-13 00:00:00', '1998-03-11 00:00:00', 2.0),
 ('BSBEV', '1998-04-14 00:00:00', '1998-03-13 00:00:00', 32.0),
 ('CACTU', '1997-04-29 00:00:00', None, None),
 ('CACTU', '1997-12-17 00:00:00', '1997-04-29 00:00:00', 232.0),
 ('CACTU', '1998-01-07 00:00:00', '1997-12-17 00:00:00', 21.0),
 ('CACTU', '1998-02-11 00:00:00', '1998-01-07 00:00:00', 35.0),
 ('CACTU', '1998-03-10 00:00:00', '1998-02-11 00:00:00', 27.0),
 ('CACTU', '1998-04-28 00:00:00', '1998-03-10 00:00:00', 49.0),
 ('CENTC', '1996-07-18 00:00:00', None, None),
 ('CHOPS', '1996-07-11 00:00:00', None, None),
 ('CHOPS', '1996-12-03 00:00:00', '1996-07-11 00:00:00', 145.0),
 ('CHOPS', '1997-04-28 00:00:00', '1996-12-03 00:00:00', 146.0),
 ('CHOPS', '1997-11-06 00:00:00', '1997-04-28 00:00:00', 192.0),
 ('CHOPS', '1997-11-19 00:00:00', '1997-11-06 00:00:00', 13.0),
 ('CHOPS', '1998-03-20 00:00:00', '1997-11-19 00:00:00', 121.0),
 ('CHOPS', '1998-04-16 00:00:00', '1998-03-20 00:00:00', 27.0),
 ('CHOPS', '1998-04-22 00:00:00', '1998-04-16 00:00:00', 6.0),
 ('COMMI', '1996-08-27 00:00:00', None, None),
 ('COMMI', '1997-03-06 00:00:00', '1996-08-27 00:00:00', 191.0),
 ('COMMI', '1997-04-02 00:00:00', '1997-03-06 00:00:00', 27.0),
 ('COMMI', '1998-03-23 00:00:00', '1997-04-02 00:00:00', 355.0),
 ('COMMI', '1998-04-22 00:00:00', '1998-03-23 00:00:00', 30.0),
 ('CONSH', '1997-02-04 00:00:00', None, None),
 ('CONSH', '1997-03-03 00:00:00', '1997-02-04 00:00:00', 27.0),
 ('CONSH', '1998-01-23 00:00:00', '1997-03-03 00:00:00', 326.0),
 ('DRACD', '1996-11-26 00:00:00', None, None),
 ('DRACD', '1996-12-23 00:00:00', '1996-11-26 00:00:00', 27.0),
 ('DRACD', '1997-12-25 00:00:00', '1996-12-23 00:00:00', 367.0),
 ('DRACD', '1998-01-09 00:00:00', '1997-12-25 00:00:00', 15.0),
 ('DRACD', '1998-04-20 00:00:00', '1998-01-09 00:00:00', 101.0),
 ('DRACD', '1998-05-04 00:00:00', '1998-04-20 00:00:00', 14.0),
 ('DUMON', '1996-09-20 00:00:00', None, None),
 ('DUMON', '1997-07-24 00:00:00', '1996-09-20 00:00:00', 307.0),
 ('DUMON', '1997-09-26 00:00:00', '1997-07-24 00:00:00', 64.0),
 ('DUMON', '1998-02-16 00:00:00', '1997-09-26 00:00:00', 143.0),
 ('EASTC', '1996-11-26 00:00:00', None, None),
 ('EASTC', '1997-01-01 00:00:00', '1996-11-26 00:00:00', 36.0),
 ('EASTC', '1997-05-09 00:00:00', '1997-01-01 00:00:00', 128.0),
 ('EASTC', '1997-11-03 00:00:00', '1997-05-09 00:00:00', 178.0),
 ('EASTC', '1998-03-31 00:00:00', '1997-11-03 00:00:00', 148.0),
 ('EASTC', '1998-04-15 00:00:00', '1998-03-31 00:00:00', 15.0),
 ('EASTC', '1998-04-24 00:00:00', '1998-04-15 00:00:00', 9.0),
 ('EASTC', '1998-04-28 00:00:00', '1998-04-24 00:00:00', 4.0),
 ('ERNSH', '1996-07-17 00:00:00', None, None),
 ('ERNSH', '1996-07-23 00:00:00', '1996-07-17 00:00:00', 6.0),
 ('ERNSH', '1996-11-11 00:00:00', '1996-07-23 00:00:00', 111.0),
 ('ERNSH', '1996-11-29 00:00:00', '1996-11-11 00:00:00', 18.0),
 ('ERNSH', '1996-12-13 00:00:00', '1996-11-29 00:00:00', 14.0),
 ('ERNSH', '1996-12-23 00:00:00', '1996-12-13 00:00:00', 10.0),
 ('ERNSH', '1997-01-02 00:00:00', '1996-12-23 00:00:00', 10.0),
 ('ERNSH', '1997-01-03 00:00:00', '1997-01-02 00:00:00', 1.0),
 ('ERNSH', '1997-01-30 00:00:00', '1997-01-03 00:00:00', 27.0),
 ('ERNSH', '1997-02-11 00:00:00', '1997-01-30 00:00:00', 12.0),
 ('ERNSH', '1997-04-22 00:00:00', '1997-02-11 00:00:00', 70.0),
 ('ERNSH', '1997-06-17 00:00:00', '1997-04-22 00:00:00', 56.0),
 ('ERNSH', '1997-07-10 00:00:00', '1997-06-17 00:00:00', 23.0),
 ('ERNSH', '1997-08-15 00:00:00', '1997-07-10 00:00:00', 36.0),
 ('ERNSH', '1997-09-12 00:00:00', '1997-08-15 00:00:00', 28.0),
 ('ERNSH', '1997-10-09 00:00:00', '1997-09-12 00:00:00', 27.0),
 ('ERNSH', '1997-12-03 00:00:00', '1997-10-09 00:00:00', 55.0),
 ('ERNSH', '1997-12-10 00:00:00', '1997-12-03 00:00:00', 7.0),
 ('ERNSH', '1997-12-11 00:00:00', '1997-12-10 00:00:00', 1.0),
 ('ERNSH', '1997-12-15 00:00:00', '1997-12-11 00:00:00', 4.0),
 ('ERNSH', '1997-12-24 00:00:00', '1997-12-15 00:00:00', 9.0),
 ('ERNSH', '1998-01-16 00:00:00', '1997-12-24 00:00:00', 23.0),
 ('ERNSH', '1998-01-27 00:00:00', '1998-01-16 00:00:00', 11.0),
 ('ERNSH', '1998-02-18 00:00:00', '1998-01-27 00:00:00', 22.0),
 ('ERNSH', '1998-03-23 00:00:00', '1998-02-18 00:00:00', 33.0),
 ('ERNSH', '1998-03-26 00:00:00', '1998-03-23 00:00:00', 3.0),
 ('ERNSH', '1998-04-01 00:00:00', '1998-03-26 00:00:00', 6.0),
 ('ERNSH', '1998-04-08 00:00:00', '1998-04-01 00:00:00', 7.0),
 ('ERNSH', '1998-04-13 00:00:00', '1998-04-08 00:00:00', 5.0),
 ('ERNSH', '1998-05-05 00:00:00', '1998-04-13 00:00:00', 22.0),
 ('FAMIA', '1996-11-06 00:00:00', None, None),
 ('FAMIA', '1996-12-18 00:00:00', '1996-11-06 00:00:00', 42.0),
 ('FAMIA', '1997-01-14 00:00:00', '1996-12-18 00:00:00', 27.0),
 ('FAMIA', '1997-04-21 00:00:00', '1997-01-14 00:00:00', 97.0),
 ('FAMIA', '1997-06-26 00:00:00', '1997-04-21 00:00:00', 66.0),
 ('FAMIA', '1997-08-29 00:00:00', '1997-06-26 00:00:00', 64.0),
 ('FAMIA', '1997-10-31 00:00:00', '1997-08-29 00:00:00', 63.0),
 ('FOLIG', '1997-01-08 00:00:00', None, None),
 ('FOLIG', '1997-03-20 00:00:00', '1997-01-08 00:00:00', 71.0),
 ('FOLIG', '1997-08-15 00:00:00', '1997-03-20 00:00:00', 148.0),
 ('FOLIG', '1997-12-03 00:00:00', '1997-08-15 00:00:00', 110.0),
 ('FOLIG', '1997-12-22 00:00:00', '1997-12-03 00:00:00', 19.0),
 ('FOLKO', '1996-07-24 00:00:00', None, None),
 ('FOLKO', '1996-10-11 00:00:00', '1996-07-24 00:00:00', 79.0),
 ('FOLKO', '1996-12-10 00:00:00', '1996-10-11 00:00:00', 60.0),
 ('FOLKO', '1997-02-03 00:00:00', '1996-12-10 00:00:00', 55.0),
 ('FOLKO', '1997-02-28 00:00:00', '1997-02-03 00:00:00', 25.0),
 ('FOLKO', '1997-05-12 00:00:00', '1997-02-28 00:00:00', 73.0),
 ('FOLKO', '1997-06-06 00:00:00', '1997-05-12 00:00:00', 25.0),
 ('FOLKO', '1997-10-14 00:00:00', '1997-06-06 00:00:00', 130.0),
 ('FOLKO', '1997-12-02 00:00:00', '1997-10-14 00:00:00', 49.0),
 ('FOLKO', '1997-12-11 00:00:00', '1997-12-02 00:00:00', 9.0),
 ('FOLKO', '1998-01-09 00:00:00', '1997-12-11 00:00:00', 29.0),
 ('FOLKO', '1998-02-10 00:00:00', '1998-01-09 00:00:00', 32.0),
 ('FOLKO', '1998-02-23 00:00:00', '1998-02-10 00:00:00', 13.0),
 ('FOLKO', '1998-03-17 00:00:00', '1998-02-23 00:00:00', 22.0),
 ('FOLKO', '1998-03-26 00:00:00', '1998-03-17 00:00:00', 9.0),
 ('FOLKO', '1998-03-27 00:00:00', '1998-03-26 00:00:00', 1.0),
 ('FOLKO', '1998-04-01 00:00:00', '1998-03-27 00:00:00', 5.0),
 ('FOLKO', '1998-04-06 00:00:00', '1998-04-01 00:00:00', 5.0),
 ('FOLKO', '1998-04-27 00:00:00', '1998-04-06 00:00:00', 21.0),
 ('FRANK', '1996-07-29 00:00:00', None, None),
 ('FRANK', '1996-10-24 00:00:00', '1996-07-29 00:00:00', 87.0),
 ('FRANK', '1996-10-30 00:00:00', '1996-10-24 00:00:00', 6.0),
 ('FRANK', '1996-12-27 00:00:00', '1996-10-30 00:00:00', 58.0),
 ('FRANK', '1997-03-27 00:00:00', '1996-12-27 00:00:00', 90.0),
 ('FRANK', '1997-06-06 00:00:00', '1997-03-27 00:00:00', 71.0),
 ('FRANK', '1997-08-07 00:00:00', '1997-06-06 00:00:00', 62.0),
 ('FRANK', '1997-09-02 00:00:00', '1997-08-07 00:00:00', 26.0),
 ('FRANK', '1997-09-16 00:00:00', '1997-09-02 00:00:00', 14.0),
 ('FRANK', '1997-09-19 00:00:00', '1997-09-16 00:00:00', 3.0),
 ('FRANK', '1997-10-24 00:00:00', '1997-09-19 00:00:00', 35.0),
 ('FRANK', '1997-12-23 00:00:00', '1997-10-24 00:00:00', 60.0),
 ('FRANK', '1998-01-29 00:00:00', '1997-12-23 00:00:00', 37.0),
 ('FRANK', '1998-03-05 00:00:00', '1998-01-29 00:00:00', 35.0),
 ('FRANK', '1998-04-09 00:00:00', '1998-03-05 00:00:00', 35.0),
 ('FRANR', '1997-09-17 00:00:00', None, None),
 ('FRANR', '1998-01-29 00:00:00', '1997-09-17 00:00:00', 134.0),
 ('FRANR', '1998-03-24 00:00:00', '1998-01-29 00:00:00', 54.0),
 ('FRANS', '1997-01-22 00:00:00', None, None),
 ('FRANS', '1997-10-20 00:00:00', '1997-01-22 00:00:00', 271.0),
 ('FRANS', '1997-11-25 00:00:00', '1997-10-20 00:00:00', 36.0),
 ('FRANS', '1997-12-31 00:00:00', '1997-11-25 00:00:00', 36.0),
 ('FRANS', '1998-04-15 00:00:00', '1997-12-31 00:00:00', 105.0),
 ('FRANS', '1998-04-30 00:00:00', '1998-04-15 00:00:00', 15.0),
 ('FURIB', '1996-10-14 00:00:00', None, None),
 ('FURIB', '1996-11-12 00:00:00', '1996-10-14 00:00:00', 29.0),
 ('FURIB', '1997-03-04 00:00:00', '1996-11-12 00:00:00', 112.0),
 ('FURIB', '1997-03-31 00:00:00', '1997-03-04 00:00:00', 27.0),
 ('FURIB', '1997-05-28 00:00:00', '1997-03-31 00:00:00', 58.0),
 ('FURIB', '1997-07-18 00:00:00', '1997-05-28 00:00:00', 51.0),
 ('FURIB', '1997-09-10 00:00:00', '1997-07-18 00:00:00', 54.0),
 ('FURIB', '1998-03-19 00:00:00', '1997-09-10 00:00:00', 190.0),
 ('GALED', '1996-11-28 00:00:00', None, None),
 ('GALED', '1997-01-27 00:00:00', '1996-11-28 00:00:00', 60.0),
 ('GALED', '1997-06-13 00:00:00', '1997-01-27 00:00:00', 137.0),
 ('GALED', '1998-02-13 00:00:00', '1997-06-13 00:00:00', 245.0),
 ('GALED', '1998-03-05 00:00:00', '1998-02-13 00:00:00', 20.0),
 ('GODOS', '1996-09-11 00:00:00', None, None),
 ('GODOS', '1997-05-28 00:00:00', '1996-09-11 00:00:00', 259.0),
 ('GODOS', '1997-08-12 00:00:00', '1997-05-28 00:00:00', 76.0),
 ('GODOS', '1998-02-05 00:00:00', '1997-08-12 00:00:00', 177.0),
 ('GODOS', '1998-02-06 00:00:00', '1998-02-05 00:00:00', 1.0),
 ('GODOS', '1998-02-16 00:00:00', '1998-02-06 00:00:00', 10.0),
 ('GODOS', '1998-02-26 00:00:00', '1998-02-16 00:00:00', 10.0),
 ('GODOS', '1998-03-13 00:00:00', '1998-02-26 00:00:00', 15.0),
 ('GODOS', '1998-04-08 00:00:00', '1998-03-13 00:00:00', 26.0),
 ('GODOS', '1998-04-21 00:00:00', '1998-04-08 00:00:00', 13.0),
 ('GOURL', '1997-01-23 00:00:00', None, None),
 ('GOURL', '1997-09-01 00:00:00', '1997-01-23 00:00:00', 221.0),
 ('GOURL', '1997-09-29 00:00:00', '1997-09-01 00:00:00', 28.0),
 ('GOURL', '1997-10-17 00:00:00', '1997-09-29 00:00:00', 18.0),
 ('GOURL', '1997-11-07 00:00:00', '1997-10-17 00:00:00', 21.0),
 ('GOURL', '1997-12-15 00:00:00', '1997-11-07 00:00:00', 38.0),
 ('GOURL', '1997-12-22 00:00:00', '1997-12-15 00:00:00', 7.0),
 ('GOURL', '1998-03-18 00:00:00', '1997-12-22 00:00:00', 86.0),
 ('GOURL', '1998-04-24 00:00:00', '1998-03-18 00:00:00', 37.0),
 ('GREAL', '1997-05-06 00:00:00', None, None),
 ('GREAL', '1997-07-04 00:00:00', '1997-05-06 00:00:00', 59.0),
 ('GREAL', '1997-07-31 00:00:00', '1997-07-04 00:00:00', 27.0),
 ('GREAL', '1997-07-31 00:00:00', '1997-07-31 00:00:00', 0.0),
 ('GREAL', '1997-09-04 00:00:00', '1997-07-31 00:00:00', 35.0),
 ('GREAL', '1997-09-25 00:00:00', '1997-09-04 00:00:00', 21.0),
 ('GREAL', '1998-01-06 00:00:00', '1997-09-25 00:00:00', 103.0),
 ('GREAL', '1998-03-09 00:00:00', '1998-01-06 00:00:00', 62.0),
 ('GREAL', '1998-04-07 00:00:00', '1998-03-09 00:00:00', 29.0),
 ('GREAL', '1998-04-22 00:00:00', '1998-04-07 00:00:00', 15.0),
 ('GREAL', '1998-04-30 00:00:00', '1998-04-22 00:00:00', 8.0),
 ('GROSR', '1996-07-30 00:00:00', None, None),
 ('GROSR', '1997-12-18 00:00:00', '1996-07-30 00:00:00', 506.0),
 ('HANAR', '1996-07-08 00:00:00', None, None),
 ('HANAR', '1996-07-10 00:00:00', '1996-07-08 00:00:00', 2.0),
 ('HANAR', '1997-05-19 00:00:00', '1996-07-10 00:00:00', 313.0),
 ('HANAR', '1997-08-26 00:00:00', '1997-05-19 00:00:00', 99.0),
 ('HANAR', '1997-10-02 00:00:00', '1997-08-26 00:00:00', 37.0),
 ('HANAR', '1997-12-09 00:00:00', '1997-10-02 00:00:00', 68.0),
 ('HANAR', '1997-12-18 00:00:00', '1997-12-09 00:00:00', 9.0),
 ('HANAR', '1998-02-13 00:00:00', '1997-12-18 00:00:00', 57.0),
 ('HANAR', '1998-02-24 00:00:00', '1998-02-13 00:00:00', 11.0),
 ('HANAR', '1998-03-03 00:00:00', '1998-02-24 00:00:00', 7.0),
 ('HANAR', '1998-03-04 00:00:00', '1998-03-03 00:00:00', 1.0),
 ('HANAR', '1998-03-27 00:00:00', '1998-03-04 00:00:00', 23.0),
 ('HANAR', '1998-04-14 00:00:00', '1998-03-27 00:00:00', 18.0),
 ('HANAR', '1998-04-27 00:00:00', '1998-04-14 00:00:00', 13.0),
 ('HILAA', '1996-07-16 00:00:00', None, None),
 ('HILAA', '1996-12-26 00:00:00', '1996-07-16 00:00:00', 163.0),
 ('HILAA', '1997-03-17 00:00:00', '1996-12-26 00:00:00', 81.0),
 ('HILAA', '1997-03-26 00:00:00', '1997-03-17 00:00:00', 9.0),
 ('HILAA', '1997-03-31 00:00:00', '1997-03-26 00:00:00', 5.0),
 ('HILAA', '1997-04-07 00:00:00', '1997-03-31 00:00:00', 7.0),
 ('HILAA', '1997-05-29 00:00:00', '1997-04-07 00:00:00', 52.0),
 ('HILAA', '1997-07-16 00:00:00', '1997-05-29 00:00:00', 48.0),
 ('HILAA', '1997-07-29 00:00:00', '1997-07-16 00:00:00', 13.0),
 ('HILAA', '1997-08-22 00:00:00', '1997-07-29 00:00:00', 24.0),
 ('HILAA', '1997-10-15 00:00:00', '1997-08-22 00:00:00', 54.0),
 ('HILAA', '1997-12-25 00:00:00', '1997-10-15 00:00:00', 71.0),
 ('HILAA', '1998-02-02 00:00:00', '1997-12-25 00:00:00', 39.0),
 ('HILAA', '1998-02-23 00:00:00', '1998-02-02 00:00:00', 21.0),
 ('HILAA', '1998-03-18 00:00:00', '1998-02-23 00:00:00', 23.0),
 ('HILAA', '1998-03-19 00:00:00', '1998-03-18 00:00:00', 1.0),
 ('HILAA', '1998-03-25 00:00:00', '1998-03-19 00:00:00', 6.0),
 ('HILAA', '1998-04-28 00:00:00', '1998-03-25 00:00:00', 34.0),
 ('HUNGC', '1996-12-06 00:00:00', None, None),
 ('HUNGC', '1996-12-25 00:00:00', '1996-12-06 00:00:00', 19.0),
 ('HUNGC', '1997-01-15 00:00:00', '1996-12-25 00:00:00', 21.0),
 ('HUNGC', '1997-07-16 00:00:00', '1997-01-15 00:00:00', 182.0),
 ('HUNGC', '1997-09-08 00:00:00', '1997-07-16 00:00:00', 54.0),
 ('HUNGO', '1996-09-05 00:00:00', None, None),
 ('HUNGO', '1996-09-19 00:00:00', '1996-09-05 00:00:00', 14.0),
 ('HUNGO', '1996-10-22 00:00:00', '1996-09-19 00:00:00', 33.0),
 ('HUNGO', '1996-12-05 00:00:00', '1996-10-22 00:00:00', 44.0),

### Exercise 4

Calculate the moving average of the quantity of the last 3 orders for each product using window functions.

In [22]:
%%sql

SELECT 
    OrderID, 
    ProductID, 
    Quantity,
    AVG(Quantity) OVER (PARTITION BY ProductID 
                        ORDER BY OrderID ROWS BETWEEN 2 PRECEDING AND 0 FOLLOWING) as MovingAvgQuantity
FROM 
    OrderDetails
ORDER BY 
    ProductID, 
    OrderID;

 * sqlite:///Northwind.db
Done.

[(10285, 1, 45, 45.0),
 (10294, 1, 18, 31.5),
 (10317, 1, 20, 27.666666666666668),
 (10348, 1, 15, 17.666666666666668),
 (10354, 1, 12, 15.666666666666666),
 (10370, 1, 15, 14.0),
 (10406, 1, 10, 12.333333333333334),
 (10413, 1, 24, 16.333333333333332),
 (10477, 1, 15, 16.333333333333332),
 (10522, 1, 40, 26.333333333333332),
 (10526, 1, 8, 21.0),
 (10576, 1, 10, 19.333333333333332),
 (10590, 1, 20, 12.666666666666666),
 (10609, 1, 3, 11.0),
 (10611, 1, 6, 9.666666666666666),
 (10628, 1, 25, 11.333333333333334),
 (10646, 1, 15, 15.333333333333334),
 (10689, 1, 35, 25.0),
 (10691, 1, 30, 26.666666666666668),
 (10700, 1, 5, 23.333333333333332),
 (10729, 1, 50, 28.333333333333332),
 (10752, 1, 8, 21.0),
 (10838, 1, 4, 20.666666666666668),
 (10847, 1, 80, 30.666666666666668),
 (10863, 1, 20, 34.666666666666664),
 (10869, 1, 40, 46.666666666666664),
 (10905, 1, 20, 26.666666666666668),
 (10911, 1, 10, 23.333333333333332),
 (10918, 1, 60, 30.0),
 (10935, 1, 21, 30.333333333333332),
 (11003, 1, 4, 28.333333333333332),
 (11005, 1, 2, 9.0),
 (11006, 1, 8, 4.666666666666667),
 (11025, 1, 10, 6.666666666666667),
 (11031, 1, 45, 21.0),
 (11035, 1, 10, 21.666666666666668),
 (11047, 1, 25, 26.666666666666668),
 (11070, 1, 40, 25.0),
 (10255, 2, 20, 20.0),
 (10258, 2, 50, 35.0),
 (10264, 2, 35, 35.0),
 (10298, 2, 40, 41.666666666666664),
 (10327, 2, 25, 33.333333333333336),
 (10335, 2, 7, 24.0),
 (10342, 2, 24, 18.666666666666668),
 (10393, 2, 25, 18.666666666666668),
 (10418, 2, 60, 36.333333333333336),
 (10435, 2, 10, 31.666666666666668),
 (10440, 2, 45, 38.333333333333336),
 (10469, 2, 40, 31.666666666666668),
 (10485, 2, 20, 35.0),
 (10504, 2, 12, 24.0),
 (10611, 2, 10, 14.0),
 (10622, 2, 20, 14.0),
 (10632, 2, 30, 20.0),
 (10641, 2, 50, 33.333333333333336),
 (10703, 2, 5, 28.333333333333332),
 (10714, 2, 30, 28.333333333333332),
 (10722, 2, 3, 12.666666666666666),
 (10741, 2, 15, 16.0),
 (10766, 2, 40, 19.333333333333332),
 (10787, 2, 15, 23.333333333333332),
 (10792, 2, 10, 21.666666666666668),
 (10806, 2, 20, 15.0),
 (10813, 2, 12, 14.0),
 (10829, 2, 10, 14.0),
 (10851, 2, 5, 9.0),
 (10852, 2, 15, 10.0),
 (10856, 2, 20, 13.333333333333334),
 (10866, 2, 21, 18.666666666666668),
 (10885, 2, 20, 20.333333333333332),
 (10888, 2, 20, 20.333333333333332),
 (10939, 2, 10, 16.666666666666668),
 (10991, 2, 50, 26.666666666666668),
 (11021, 2, 11, 23.666666666666668),
 (11030, 2, 100, 53.666666666666664),
 (11041, 2, 30, 47.0),
 (11049, 2, 10, 46.666666666666664),
 (11070, 2, 20, 20.0),
 (11072, 2, 8, 12.666666666666666),
 (11075, 2, 10, 12.666666666666666),
 (11077, 2, 24, 14.0),
 (10289, 3, 30, 30.0),
 (10405, 3, 50, 40.0),
 (10485, 3, 20, 33.333333333333336),
 (10540, 3, 60, 43.333333333333336),
 (10591, 3, 14, 31.333333333333332),
 (10702, 3, 6, 26.666666666666668),
 (10742, 3, 20, 13.333333333333334),
 (10764, 3, 20, 15.333333333333334),
 (10849, 3, 49, 29.666666666666668),
 (10857, 3, 30, 33.0),
 (11017, 3, 25, 34.666666666666664),
 (11077, 3, 4, 19.666666666666668),
 (10309, 4, 20, 20.0),
 (10326, 4, 24, 22.0),
 (10336, 4, 18, 20.666666666666668),
 (10339, 4, 10, 17.333333333333332),
 (10344, 4, 35, 21.0),
 (10464, 4, 16, 20.333333333333332),
 (10511, 4, 50, 33.666666666666664),
 (10527, 4, 50, 38.666666666666664),
 (10533, 4, 50, 50.0),
 (10606, 4, 20, 40.0),
 (10635, 4, 10, 26.666666666666668),
 (10636, 4, 25, 18.333333333333332),
 (10654, 4, 12, 15.666666666666666),
 (10704, 4, 6, 14.333333333333334),
 (10726, 4, 25, 14.333333333333334),
 (10846, 4, 21, 17.333333333333332),
 (10913, 4, 30, 25.333333333333332),
 (10950, 4, 5, 18.666666666666668),
 (11000, 4, 25, 20.0),
 (11077, 4, 1, 10.333333333333334),
 (10258, 5, 65, 65.0),
 (10262, 5, 12, 38.5),
 (10290, 5, 20, 32.333333333333336),
 (10382, 5, 32, 21.333333333333332),
 (10635, 5, 15, 22.333333333333332),
 (10708, 5, 4, 17.0),
 (10848, 5, 30, 16.333333333333332),
 (10958, 5, 20, 18.0),
 (11030, 5, 70, 40.0),
 (11047, 5, 30, 40.0),
 (10309, 6, 30, 30.0),
 (10325, 6, 6, 18.0),
 (10618, 6, 70, 35.333333333333336),
 (10734, 6, 30, 35.333333333333336),
 (10830, 6, 6, 35.333333333333336),
 (10871, 6, 50, 28.666666666666668),
 (10934, 6, 20, 25.333333333333332),
 (10949, 6, 12, 27.333333333333332),
 (10952, 6, 16, 16.0),
 (10989, 6, 40, 22.666666666666668),
 (11076, 6, 20, 25.333333333333332),
 (11077, 6, 1, 20.333333333333332),
 (10262, 7, 15, 15.0),
 (10385, 7, 10, 12.5),
 (10459, 7, 16, 13.666666666666666),
 (10471, 7, 30, 18.666666666666668),
 (10511, 7, 50, 32.0),
 (10546, 7, 10, 30.0),
 (10591, 7, 10, 23.333333333333332),
 (10607, 7, 45, 21.666666666666668),
 (10634, 7, 35, 30.0),
 (10694, 7, 90, 56.666666666666664),
 (10766, 7, 35, 53.333333333333336),
 (10790, 7, 3, 42.666666666666664),
 (10833, 7, 20, 19.333333333333332),
 (10858, 7, 5, 9.333333333333334),
 (10908, 7, 20, 15.0),
 (10909, 7, 12, 12.333333333333334),
 (10940, 7, 8, 13.333333333333334),
 (10958, 7, 6, 8.666666666666666),
 (10962, 7, 45, 19.666666666666668),
 (10979, 7, 18, 23.0),
 (10982, 7, 20, 27.666666666666668),
 (10987, 7, 60, 32.666666666666664),
 (10988, 7, 60, 46.666666666666664),
 (11001, 7, 60, 60.0),
 (11010, 7, 20, 46.666666666666664),
 (11023, 7, 4, 28.0),
 (11056, 7, 40, 21.333333333333332),
 (11071, 7, 15, 19.666666666666668),
 (11077, 7, 1, 18.666666666666668),
 (10344, 8, 70, 70.0),
 (10345, 8, 70, 70.0),
 (10511, 8, 10, 50.0),
 (10522, 8, 24, 34.666666666666664),
 (10695, 8, 10, 14.666666666666666),
 (10709, 8, 40, 24.666666666666668),
 (10786, 8, 30, 26.666666666666668),
 (10829, 8, 20, 30.0),
 (10893, 8, 30, 26.666666666666668),
 (10975, 8, 16, 22.0),
 (10978, 8, 20, 22.0),
 (11007, 8, 30, 22.0),
 (11077, 8, 2, 17.333333333333332),
 (10420, 9, 20, 20.0),
 (10515, 9, 16, 18.0),
 (10687, 9, 50, 28.666666666666668),
 (10693, 9, 6, 24.0),
 (10848, 9, 3, 19.666666666666668),
 (10273, 10, 24, 24.0),
 (10276, 10, 15, 19.5),
 (10357, 10, 30, 23.0),
 (10389, 10, 16, 20.333333333333332),
 (10449, 10, 14, 20.0),
 (10450, 10, 20, 16.666666666666668),
 (10478, 10, 20, 18.0),
 (10519, 10, 16, 18.666666666666668),
 (10524, 10, 2, 12.666666666666666),
 (10568, 10, 5, 7.666666666666667),
 (10609, 10, 10, 5.666666666666667),
 (10612, 10, 70, 28.333333333333332),
 (10646, 10, 18, 32.666666666666664),
 (10664, 10, 24, 37.333333333333336),
 (10676, 10, 2, 14.666666666666666),
 (10685, 10, 20, 15.333333333333334),
 (10688, 10, 18, 13.333333333333334),
 (10713, 10, 18, 18.666666666666668),
 (10715, 10, 21, 19.0),
 (10724, 10, 16, 18.333333333333332),
 (10775, 10, 6, 14.333333333333334),
 (10785, 10, 10, 10.666666666666666),
 (10804, 10, 36, 17.333333333333332),
 (10827, 10, 15, 20.333333333333332),
 (10841, 10, 16, 22.333333333333332),
 (10854, 10, 100, 43.666666666666664),
 (10874, 10, 10, 42.0),
 (10886, 10, 70, 60.0),
 (10924, 10, 20, 33.333333333333336),
 (10946, 10, 25, 38.333333333333336),
 (10949, 10, 30, 25.0),
 (11020, 10, 24, 26.333333333333332),
 (11077, 10, 1, 18.333333333333332),
 (10248, 11, 12, 12.0),
 (10296, 11, 12, 12.0),
 (10327, 11, 50, 24.666666666666668),
 (10353, 11, 12, 24.666666666666668),
 (10365, 11, 24, 28.666666666666668),
 (10407, 11, 30, 22.0),
 (10434, 11, 6, 20.0),
 (10442, 11, 30, 22.0),
 (10443, 11, 6, 14.0),
 (10466, 11, 10, 15.333333333333334),
 (10486, 11, 5, 7.0),
 (10489, 11, 15, 10.0),
 (10528, 11, 3, 7.666666666666667),
 (10535, 11, 50, 22.666666666666668),
 (10542, 11, 15, 22.666666666666668),
 (10545, 11, 10, 25.0),
 (10553, 11, 15, 13.333333333333334),
 (10566, 11, 35, 20.0),
 (10570, 11, 15, 21.666666666666668),
 (10614, 11, 14, 21.333333333333332),
 (10637, 11, 10, 13.0),
 (10698, 11, 15, 13.0),
 (10726, 11, 5, 10.0),
 (10770, 11, 15, 11.666666666666666),
 (10797, 11, 20, 13.333333333333334),
 (10800, 11, 50, 28.333333333333332),
 (10823, 11, 20, 30.0),
 (10842, 11, 15, 28.333333333333332),
 (10862, 11, 25, 20.0),
 (10869, 11, 10, 16.666666666666668),
 (10889, 11, 40, 25.0),
 (10912, 11, 40, 30.0),
 (10926, 11, 2, 27.333333333333332),
 (10944, 11, 5, 15.666666666666666),
 (10986, 11, 30, 12.333333333333334),
 (10989, 11, 15, 16.666666666666668),
 (11043, 11, 10, 18.333333333333332),
 (11073, 11, 10, 11.666666666666666),
 (10266, 12, 12, 12.0),
 (10439, 12, 15, 13.5),
 (10536, 12, 15, 14.0),
 (10543, 12, 30, 20.0),
 (10633, 12, 36, 27.0),
 (10678, 12, 100, 55.333333333333336),
 (10695, 12, 4, 46.666666666666664),
 (10718, 12, 36, 46.666666666666664),
 (10968, 12, 30, 23.333333333333332),
 (10979, 12, 20, 28.666666666666668),
 (11018, 12, 20, 23.333333333333332),
 (11046, 12, 20, 20.0),
 (11049, 12, 4, 14.666666666666666),
 (11077, 12, 2, 8.666666666666666),
 (10276, 13, 10, 10.0),
 (10291, 13, 20, 15.0),
 (10325, 13, 12, 14.0),
 (10383, 13, 20, 17.333333333333332),
 (10391, 13, 18, 16.666666666666668),
 (10394, 13, 10, 16.0),
 (10420, 13, 2, 10.0),
 (10462, 13, 1, 4.333333333333333),
 (10508, 13, 10, 4.333333333333333),
 (10526, 13, 10, 7.0),
 (10539, 13, 8, 9.333333333333334),
 (10601, 13, 60, 26.0),
 (10613, 13, 8, 25.333333333333332),
 (10633, 13, 13, 27.0),
 (10737, 13, 4, 8.333333333333334),
 (10746, 13, 6, 7.666666666666667),
 (10799, 13, 20, 10.0),
 (10810, 13, 7, 11.0),
 (10829, 13, 10, 12.333333333333334),
 (10832, 13, 3, 6.666666666666667),
 (10837, 13, 6, 6.333333333333333),
 (10854, 13, 65, 24.666666666666668),
 (10894, 13, 28, 33.0),
 (10898, 13, 5, 32.666666666666664),
 (10903, 13, 40, 24.333333333333332),
 (10926, 13, 10, 18.333333333333332),
 (10931, 13, 42, 30.666666666666668),
 (10938, 13, 20, 24.0),
 (10940, 13, 20, 27.333333333333332),
 (10943, 13, 15, 18.333333333333332),
 (10945, 13, 20, 18.333333333333332),
 (10962, 13, 77, 37.333333333333336),
 (10983, 13, 84, 60.333333333333336),
 (11002, 13, 56, 72.33333333333333),
 (11025, 13, 20, 53.333333333333336),
 (11031, 13, 80, 52.0),
 (11036, 13, 7, 35.666666666666664),
 (11059, 13, 30, 39.0),
 (11071, 13, 10, 15.666666666666666),
 (11077, 13, 4, 14.666666666666666),
 (10249, 14, 9, 9.0),
 (10325, 14, 9, 9.0),
 (10333, 14, 10, 9.333333333333334),
 (10375, 14, 15, 11.333333333333334),
 (10393, 14, 42, 22.333333333333332),
 (10409, 14, 12, 23.0),
 (10412, 14, 20, 24.666666666666668),
 (10427, 14, 35, 22.333333333333332),
 (10474, 14, 12, 22.333333333333332),
 (10503, 14, 70, 39.0),
 (10555, 14, 30, 37.333333333333336),
 (10571, 14, 11, 37.0),
 (10580, 14, 15, 18.666666666666668),
 (10623, 14, 21, 15.666666666666666),
 (10625, 14, 3, 13.0),
 (10656, 14, 3, 9.0),
 (10675, 14, 30, 12.0),
 (10733, 14, 16, 16.333333333333332),
 (10750, 14, 5, 17.0),
 (10794, 14, 15, 12.0),
 (11076, 14, 20, 13.333333333333334),
 (11077, 14, 1, 12.0),
 (10283, 15, 20, 20.0),
 (10323, 15, 5, 12.5),
 (10500, 15, 12, 12.333333333333334),
 (10579, 15, 10, 9.0),
 (10592, 15, 25, 15.666666666666666),
 (10657, 15, 50, 28.333333333333332),
 (10255, 16, 35, 35.0),
 (10263, 16, 60, 47.5),
 (10287, 16, 40, 45.0),
 (10296, 16, 30, 43.333333333333336),
 (10310, 16, 10, 26.666666666666668),
 (10324, 16, 21, 20.333333333333332),
 (10359, 16, 56, 29.0),
 (10403, 16, 21, 32.666666666666664),
 (10439, 16, 16, 31.0),
 (10440, 16, 49, 28.666666666666668),
 (10454, 16, 20, 28.333333333333332),
 (10469, 16, 35, 34.666666666666664),
 (10489, 16, 18, 24.333333333333332),
 (10515, 16, 50, 34.333333333333336),
 (10551, 16, 40, 36.0),
 (10553, 16, 14, 34.666666666666664),
 (10554, 16, 30, 28.0),
 (10572, 16, 12, 18.666666666666668),
 (10605, 16, 30, 24.0),
 (10653, 16, 30, 24.0),
 (10671, 16, 10, 23.333333333333332),
 (10673, 16, 3, 14.333333333333334),
 (10680, 16, 50, 21.0),
 (10706, 16, 20, 24.333333333333332),
 (10718, 16, 20, 30.0),
 (10730, 16, 15, 18.333333333333332),
 (10738, 16, 3, 12.666666666666666),
 (10779, 16, 20, 12.666666666666666),
 (10795, 16, 65, 29.333333333333332),
 (10855, 16, 50, 45.0),
 (10871, 16, 12, 42.333333333333336),
 (10877, 16, 30, 30.666666666666668),
 (10909, 16, 15, 19.0),
 (10916, 16, 6, 17.0),
 (10919, 16, 24, 15.0),
 (10932, 16, 30, 20.0),
 (10954, 16, 28, 27.333333333333332),
 (10984, 16, 55, 37.666666666666664),
 (10985, 16, 36, 39.666666666666664),
 (11066, 16, 3, 31.333333333333332),
 (11070, 16, 30, 23.0),
 (11074, 16, 14, 15.666666666666666),
 (11077, 16, 2, 15.333333333333334),
 (10265, 17, 30, 30.0),
 (10279, 17, 15, 22.5),
 (10294, 17, 15, 20.0),
 (10302, 17, 40, 23.333333333333332),
 (10319, 17, 8, 21.0),
 (10338, 17, 20, 22.666666666666668),
 (10339, 17, 70, 32.666666666666664),
 (10346, 17, 36, 42.0),
 (10415, 17, 2, 36.0),
 (10430, 17, 45, 27.666666666666668),
 (10431, 17, 50, 32.333333333333336),
 (10444, 17, 10, 35.0),
 (10523, 17, 25, 28.333333333333332),
 (10530, 17, 40, 25.0),
 (10550, 17, 8, 24.333333333333332),
 (10564, 17, 16, 21.333333333333332),
 (10573, 17, 18, 14.0),
 (10607, 17, 100, 44.666666666666664),
 (10686, 17, 30, 49.333333333333336),
 (10696, 17, 20, 50.0),
 (10698, 17, 8, 19.333333333333332),
 (10714, 17, 27, 18.333333333333332),
 (10727, 17, 20, 18.333333333333332),
 (10773, 17, 33, 26.666666666666668),
 (10795, 17, 35, 29.333333333333332),
 (10801, 17, 40, 36.0),
 (10852, 17, 6, 27.0),
 (10861, 17, 42, 29.333333333333332),
 (10871, 17, 16, 21.333333333333332),
 (10890, 17, 15, 24.333333333333332),
 (10911, 17, 12, 14.333333333333334),
 (10915, 17, 10, 12.333333333333334),
 (10922, 17, 15, 12.333333333333334),
 (10949, 17, 6, 10.333333333333334),
 (10972, 17, 6, 9.0),
 (11059, 17, 12, 8.0),
 (11064, 17, 77, 31.666666666666668),
 (10293, 18, 12, 12.0),
 (10305, 18, 25, 18.5),
 (10332, 18, 40, 25.666666666666668),
 (10340, 18, 20, 28.333333333333332),
 (10382, 18, 9, 23.0),
 (10470, 18, 30, 19.666666666666668),
 (10516, 18, 25, 21.333333333333332),
 (10566, 18, 18, 24.333333333333332),
 (10588, 18, 40, 27.666666666666668),
 (10634, 18, 50, 36.0),
 (10639, 18, 8, 32.666666666666664),
 (10644, 18, 4, 20.666666666666668),
 (10645, 18, 20, 10.666666666666666),
 (10719, 18, 12, 12.0),
 (10745, 18, 24, 18.666666666666668),
 (10756, 18, 21, 19.0),
 (10789, 18, 30, 25.0),
 (10838, 18, 25, 25.333333333333332),
 (10853, 18, 10, 21.666666666666668),
 (10861, 18, 20, 18.333333333333332),
 (10877, 18, 25, 18.333333333333332),
 (10935, 18, 4, 16.333333333333332),
 (10964, 18, 6, 11.666666666666666),
 (10985, 18, 8, 6.0),
 (11018, 18, 10, 8.0),
 (11026, 18, 8, 8.666666666666666),
 (11053, 18, 35, 17.666666666666668),
 (10281, 19, 1, 1.0),
 (10283, 19, 18, 9.5),
 (10299, 19, 15, 11.333333333333334),
 (10329, 19, 10, 14.333333333333334),
 (10345, 19, 80, 35.0),
 (10414, 19, 18, 36.0),
 (10416, 19, 20, 39.333333333333336),
 (10421, 19, 4, 14.0),
 (10438, 19, 15, 13.0),
 (10446, 19, 12, 10.333333333333334),
 (10447, 19, 40, 22.333333333333332),
 (10463, 19, 21, 24.333333333333332),
 (10487, 19, 5, 22.0),
 (10550, 19, 10, 12.0),
 (10555, 19, 35, 16.666666666666668),
 (10621, 19, 5, 16.666666666666668),
 (10623, 19, 15, 18.333333333333332),
 (10647, 19, 30, 16.666666666666668),
 (10651, 19, 12, 19.0),
 (10676, 19, 7, 16.333333333333332),
 (10681, 19, 30, 16.333333333333332),
 (10697, 19, 7, 14.666666666666666),
 (10710, 19, 5, 14.0),
 (10711, 19, 12, 8.0),
 (10788, 19, 50, 22.333333333333332),
 (10803, 19, 24, 28.666666666666668),
 (10811, 19, 15, 29.666666666666668),
 (10831, 19, 2, 13.666666666666666),
 (10847, 19, 12, 9.666666666666666),
 (10875, 19, 25, 13.0),
 (10910, 19, 12, 16.333333333333332),
 (10926, 19, 7, 14.666666666666666),
 (10967, 19, 12, 10.333333333333334),
 (11012, 19, 50, 23.0),
 (11022, 19, 35, 32.333333333333336),
 (11066, 19, 42, 42.333333333333336),
 (11076, 19, 10, 29.0),
 (10252, 20, 40, 40.0),
 (10272, 20, 6, 23.0),
 (10292, 20, 20, 22.0),
 (10372, 20, 12, 12.666666666666666),
 (10384, 20, 28, 20.0),
 (10514, 20, 39, 26.333333333333332),
 (10523, 20, 15, 27.333333333333332),
 (10593, 20, 21, 25.0),
 (10660, 20, 21, 19.0),
 (10828, 20, 5, 15.666666666666666),
 (10878, 20, 20, 15.333333333333334),
 (10927, 20, 5, 10.0),
 (10953, 20, 50, 25.0),
 (10986, 20, 15, 23.333333333333332),
 (11021, 20, 15, 26.666666666666668),
 (11077, 20, 1, 10.333333333333334),
 (10259, 21, 10, 10.0),
 (10261, 21, 20, 15.0),
 (10333, 21, 10, 13.333333333333334),
 (10368, 21, 5, 11.666666666666666),
 (10397, 21, 10, 8.333333333333334),
 (10406, 21, 30, 15.0),
 (10409, 21, 12, 17.333333333333332),
 (10430, 21, 50, 30.666666666666668),
 (10456, 21, 40, 34.0),
 (10461, 21, 40, 43.333333333333336),
 (10477, 21, 21, 33.666666666666664),
 (10484, 21, 14, 25.0),
 (10504, 21, 12, 15.666666666666666),
 (10513, 21, 40, 22.0),
 (10539, 21, 15, 22.333333333333332),
 (10550, 21, 6, 20.333333333333332),
 (10609, 21, 6, 9.0),
 (10614, 21, 8, 6.666666666666667),
 (10619, 21, 42, 18.666666666666668),
 (10623, 21, 25, 25.0),
 (10642, 21, 30, 32.333333333333336),
 (10658, 21, 60, 38.333333333333336),
 (10681, 21, 12, 34.0),
 (10716, 21, 5, 25.666666666666668),
 (10717, 21, 32, 16.333333333333332),
 (10729, 21, 30, 22.333333333333332),
 (10731, 21, 40, 34.0),
 (10763, 21, 40, 36.666666666666664),
 (10861, 21, 40, 40.0),
 (10873, 21, 20, 33.333333333333336),
 (10884, 21, 40, 33.333333333333336),
 (10929, 21, 60, 40.0),
 (10930, 21, 36, 45.333333333333336),
 (10956, 21, 12, 36.0),
 (10978, 21, 40, 29.333333333333332),
 (10990, 21, 65, 39.0),
 (11034, 21, 15, 40.0),
 (11040, 21, 20, 33.333333333333336),
 (11058, 21, 3, 12.666666666666666),
 (10251, 22, 6, 6.0),
 (10435, 22, 12, 9.0),
 (10553, 22, 24, 14.0),
 (10603, 22, 48, 28.0),
 (10619, 22, 40, 37.333333333333336),
 (10635, 22, 40, 42.666666666666664),
 (10648, 22, 15, 31.666666666666668),
 (10651, 22, 20, 25.0),
 (10763, 22, 6, 13.666666666666666),
 (10768, 22, 4, 10.0),
 (10836, 22, 52, 20.666666666666668),
 (10844, 22, 35, 30.333333333333332),
 (10943, 22, 21, 36.0),
 (11001, 22, 25, 27.0),
 (10337, 23, 40, 40.0),
 (10348, 23, 25, 32.5),
 (10396, 23, 40, 35.0),
 (10402, 23, 60, 41.666666666666664),
 (10462, 23, 21, 40.333333333333336),
 (10470, 23, 15, 32.0),
 (10495, 23, 10, 15.333333333333334),
 (10543, 23, 70, 31.666666666666668),
 (10554, 23, 20, 33.333333333333336),
 (10621, 23, 10, 33.333333333333336),
 (10670, 23, 32, 20.666666666666668),
 (10674, 23, 5, 15.666666666666666),
 (10748, 23, 44, 27.0),
 (10811, 23, 18, 22.333333333333332),
 (10845, 23, 70, 44.0),
 (10869, 23, 50, 46.0),
 (10880, 23, 30, 50.0),
 (10935, 23, 8, 29.333333333333332),
 (11013, 23, 10, 16.0),
 (11077, 23, 2, 6.666666666666667),
 (10254, 24, 15, 15.0),
 (10263, 24, 28, 21.5),
 (10275, 24, 12, 18.333333333333332),
 (10280, 24, 12, 17.333333333333332),
 (10281, 24, 6, 10.0),
 (10293, 24, 10, 9.333333333333334),
 (10352, 24, 10, 8.666666666666666),
 (10355, 24, 25, 15.0),
 (10358, 24, 10, 15.0),
 (10386, 24, 15, 16.666666666666668),
 (10387, 24, 15, 13.333333333333334),
 (10446, 24, 20, 16.666666666666668),
 (10465, 24, 25, 20.0),
 (10467, 24, 28, 24.333333333333332),
 (10472, 24, 80, 44.333333333333336),
 (10498, 24, 14, 40.666666666666664),
 (10512, 24, 10, 34.666666666666664),
 (10518, 24, 5, 9.666666666666666),
 (10520, 24, 8, 7.666666666666667),
 (10541, 24, 35, 16.0),
 (10555, 24, 18, 20.333333333333332),
 (10565, 24, 25, 26.0),
 (10597, 24, 35, 26.0),
 (10620, 24, 5, 21.666666666666668),
 (10623, 24, 3, 14.333333333333334),
 (10648, 24, 15, 7.666666666666667),
 (10695, 24, 20, 12.666666666666666),
 (10704, 24, 35, 23.333333333333332),
 (10763, 24, 20, 25.0),
 (10799, 24, 20, 25.0),
 (10859, 24, 40, 26.666666666666668),
 (10866, 24, 6, 22.0),
 (10883, 24, 8, 18.0),
 (10885, 24, 12, 8.666666666666666),
 (10893, 24, 10, 10.0),
 (10895, 24, 110, 44.0),
 (10922, 24, 35, 51.666666666666664),
 (10946, 24, 25, 56.666666666666664),
 (10960, 24, 10, 23.333333333333332),
 (10968, 24, 30, 21.666666666666668),
 (10979, 24, 80, 40.0),
 (10984, 24, 20, 43.333333333333336),
 (10998, 24, 12, 37.333333333333336),
 (11000, 24, 30, 20.666666666666668),
 (11009, 24, 12, 18.0),
 (11010, 24, 10, 17.333333333333332),
 (11027, 24, 30, 17.333333333333332),
 (11031, 24, 21, 20.333333333333332),
 (11051, 24, 10, 20.333333333333332),
 (11055, 24, 15, 15.333333333333334),
 (11073, 24, 20, 15.0),
 (10323, 25, 4, 4.0),
 (10347, 25, 10, 7.0),
 (10362, 25, 50, 21.333333333333332),

## Solutions

### Exercise 1

In [ ]:
%%sql

SELECT 
    OrderID, 
    OrderDate,
    RANK() OVER (ORDER BY OrderDate DESC) as Order_rank
FROM 
    Orders 
WHERE 
    CustomerID = 'ALFKI';

The `RANK()` window function is used here to rank each order of the customer with the ID `'ALFKI'` based on the `OrderDate`. The `DESC` keyword is used so that the most recent order gets the highest rank (i.e. 1).

### Exercise 2

In [ ]:
%%sql

SELECT 
    OrderID, 
    Quantity, 
    SUM(Quantity) OVER (
    ORDER BY OrderID) as RunningTotal 
FROM 
    OrderDetails
GROUP BY 
    OrderID;

The `SUM()` window function is used here to calculate a running total of the quantity of orders. The `ORDER BY` clause inside the `OVER()` clause ensures that the running total is calculated in the order of the `OrderID`. We then group our data by `OrderID`.

### Exercise 3

In [19]:
%%sql

SELECT 
    CustomerID, 
    OrderDate, 
    LAG(OrderDate, 1) OVER 
        (PARTITION BY CustomerID 
        ORDER BY OrderDate) as PrevOrderDate, 
    julianday(OrderDate)-
    julianday(LAG(OrderDate, 1) OVER
            (PARTITION BY CustomerID 
            ORDER BY OrderDate)) as DateDiff
FROM 
    Orders;

 * sqlite:///Northwind.db
Done.

[('ALFKI', '1997-08-25 00:00:00', None, None),
 ('ALFKI', '1997-10-03 00:00:00', '1997-08-25 00:00:00', 39.0),
 ('ALFKI', '1997-10-13 00:00:00', '1997-10-03 00:00:00', 10.0),
 ('ALFKI', '1998-01-15 00:00:00', '1997-10-13 00:00:00', 94.0),
 ('ALFKI', '1998-03-16 00:00:00', '1998-01-15 00:00:00', 60.0),
 ('ALFKI', '1998-04-09 00:00:00', '1998-03-16 00:00:00', 24.0),
 ('ANATR', '1996-09-18 00:00:00', None, None),
 ('ANATR', '1997-08-08 00:00:00', '1996-09-18 00:00:00', 324.0),
 ('ANATR', '1997-11-28 00:00:00', '1997-08-08 00:00:00', 112.0),
 ('ANATR', '1998-03-04 00:00:00', '1997-11-28 00:00:00', 96.0),
 ('ANTON', '1996-11-27 00:00:00', None, None),
 ('ANTON', '1997-04-15 00:00:00', '1996-11-27 00:00:00', 139.0),
 ('ANTON', '1997-05-13 00:00:00', '1997-04-15 00:00:00', 28.0),
 ('ANTON', '1997-06-19 00:00:00', '1997-05-13 00:00:00', 37.0),
 ('ANTON', '1997-09-22 00:00:00', '1997-06-19 00:00:00', 95.0),
 ('ANTON', '1997-09-25 00:00:00', '1997-09-22 00:00:00', 3.0),
 ('ANTON', '1998-01-28 00:00:00', '1997-09-25 00:00:00', 125.0),
 ('AROUT', '1996-11-15 00:00:00', None, None),
 ('AROUT', '1996-12-16 00:00:00', '1996-11-15 00:00:00', 31.0),
 ('AROUT', '1997-02-21 00:00:00', '1996-12-16 00:00:00', 67.0),
 ('AROUT', '1997-06-04 00:00:00', '1997-02-21 00:00:00', 103.0),
 ('AROUT', '1997-10-16 00:00:00', '1997-06-04 00:00:00', 134.0),
 ('AROUT', '1997-11-14 00:00:00', '1997-10-16 00:00:00', 29.0),
 ('AROUT', '1997-11-17 00:00:00', '1997-11-14 00:00:00', 3.0),
 ('AROUT', '1997-12-08 00:00:00', '1997-11-17 00:00:00', 21.0),
 ('AROUT', '1997-12-24 00:00:00', '1997-12-08 00:00:00', 16.0),
 ('AROUT', '1998-02-02 00:00:00', '1997-12-24 00:00:00', 40.0),
 ('AROUT', '1998-03-03 00:00:00', '1998-02-02 00:00:00', 29.0),
 ('AROUT', '1998-03-16 00:00:00', '1998-03-03 00:00:00', 13.0),
 ('AROUT', '1998-04-10 00:00:00', '1998-03-16 00:00:00', 25.0),
 ('BERGS', '1996-08-12 00:00:00', None, None),
 ('BERGS', '1996-08-14 00:00:00', '1996-08-12 00:00:00', 2.0),
 ('BERGS', '1996-12-16 00:00:00', '1996-08-14 00:00:00', 124.0),
 ('BERGS', '1997-02-12 00:00:00', '1996-12-16 00:00:00', 58.0),
 ('BERGS', '1997-02-13 00:00:00', '1997-02-12 00:00:00', 1.0),
 ('BERGS', '1997-05-01 00:00:00', '1997-02-13 00:00:00', 77.0),
 ('BERGS', '1997-06-18 00:00:00', '1997-05-01 00:00:00', 48.0),
 ('BERGS', '1997-08-11 00:00:00', '1997-06-18 00:00:00', 54.0),
 ('BERGS', '1997-09-02 00:00:00', '1997-08-11 00:00:00', 22.0),
 ('BERGS', '1997-09-17 00:00:00', '1997-09-02 00:00:00', 15.0),
 ('BERGS', '1997-10-01 00:00:00', '1997-09-17 00:00:00', 14.0),
 ('BERGS', '1997-11-07 00:00:00', '1997-10-01 00:00:00', 37.0),
 ('BERGS', '1997-12-16 00:00:00', '1997-11-07 00:00:00', 39.0),
 ('BERGS', '1998-01-16 00:00:00', '1997-12-16 00:00:00', 31.0),
 ('BERGS', '1998-01-28 00:00:00', '1998-01-16 00:00:00', 12.0),
 ('BERGS', '1998-02-03 00:00:00', '1998-01-28 00:00:00', 6.0),
 ('BERGS', '1998-02-06 00:00:00', '1998-02-03 00:00:00', 3.0),
 ('BERGS', '1998-03-04 00:00:00', '1998-02-06 00:00:00', 26.0),
 ('BLAUS', '1997-04-09 00:00:00', None, None),
 ('BLAUS', '1997-04-17 00:00:00', '1997-04-09 00:00:00', 8.0),
 ('BLAUS', '1997-06-27 00:00:00', '1997-04-17 00:00:00', 71.0),
 ('BLAUS', '1997-07-29 00:00:00', '1997-06-27 00:00:00', 32.0),
 ('BLAUS', '1998-01-27 00:00:00', '1997-07-29 00:00:00', 182.0),
 ('BLAUS', '1998-03-17 00:00:00', '1998-01-27 00:00:00', 49.0),
 ('BLAUS', '1998-04-29 00:00:00', '1998-03-17 00:00:00', 43.0),
 ('BLONP', '1996-07-25 00:00:00', None, None),
 ('BLONP', '1996-09-04 00:00:00', '1996-07-25 00:00:00', 41.0),
 ('BLONP', '1996-11-22 00:00:00', '1996-09-04 00:00:00', 79.0),
 ('BLONP', '1997-02-05 00:00:00', '1996-11-22 00:00:00', 75.0),
 ('BLONP', '1997-02-18 00:00:00', '1997-02-05 00:00:00', 13.0),
 ('BLONP', '1997-06-05 00:00:00', '1997-02-18 00:00:00', 107.0),
 ('BLONP', '1997-06-12 00:00:00', '1997-06-05 00:00:00', 7.0),
 ('BLONP', '1997-06-30 00:00:00', '1997-06-12 00:00:00', 18.0),
 ('BLONP', '1997-08-12 00:00:00', '1997-06-30 00:00:00', 43.0),
 ('BLONP', '1997-09-23 00:00:00', '1997-08-12 00:00:00', 42.0),
 ('BLONP', '1998-01-12 00:00:00', '1997-09-23 00:00:00', 111.0),
 ('BOLID', '1996-10-10 00:00:00', None, None),
 ('BOLID', '1997-12-29 00:00:00', '1996-10-10 00:00:00', 445.0),
 ('BOLID', '1998-03-24 00:00:00', '1997-12-29 00:00:00', 85.0),
 ('BONAP', '1996-10-16 00:00:00', None, None),
 ('BONAP', '1996-10-29 00:00:00', '1996-10-16 00:00:00', 13.0),
 ('BONAP', '1996-11-25 00:00:00', '1996-10-29 00:00:00', 27.0),
 ('BONAP', '1997-03-11 00:00:00', '1996-11-25 00:00:00', 106.0),
 ('BONAP', '1997-04-18 00:00:00', '1997-03-11 00:00:00', 38.0),
 ('BONAP', '1997-05-02 00:00:00', '1997-04-18 00:00:00', 14.0),
 ('BONAP', '1997-09-10 00:00:00', '1997-05-02 00:00:00', 131.0),
 ('BONAP', '1997-10-23 00:00:00', '1997-09-10 00:00:00', 43.0),
 ('BONAP', '1997-11-05 00:00:00', '1997-10-23 00:00:00', 13.0),
 ('BONAP', '1997-11-06 00:00:00', '1997-11-05 00:00:00', 1.0),
 ('BONAP', '1997-11-26 00:00:00', '1997-11-06 00:00:00', 20.0),
 ('BONAP', '1998-01-12 00:00:00', '1997-11-26 00:00:00', 47.0),
 ('BONAP', '1998-02-05 00:00:00', '1998-01-12 00:00:00', 24.0),
 ('BONAP', '1998-02-09 00:00:00', '1998-02-05 00:00:00', 4.0),
 ('BONAP', '1998-03-06 00:00:00', '1998-02-09 00:00:00', 25.0),
 ('BONAP', '1998-03-11 00:00:00', '1998-03-06 00:00:00', 5.0),
 ('BONAP', '1998-05-06 00:00:00', '1998-03-11 00:00:00', 56.0),
 ('BOTTM', '1996-12-20 00:00:00', None, None),
 ('BOTTM', '1997-01-10 00:00:00', '1996-12-20 00:00:00', 21.0),
 ('BOTTM', '1997-01-10 00:00:00', '1997-01-10 00:00:00', 0.0),
 ('BOTTM', '1997-01-30 00:00:00', '1997-01-10 00:00:00', 20.0),
 ('BOTTM', '1997-04-01 00:00:00', '1997-01-30 00:00:00', 61.0),
 ('BOTTM', '1997-11-14 00:00:00', '1997-04-01 00:00:00', 227.0),
 ('BOTTM', '1998-03-02 00:00:00', '1997-11-14 00:00:00', 108.0),
 ('BOTTM', '1998-03-12 00:00:00', '1998-03-02 00:00:00', 10.0),
 ('BOTTM', '1998-03-13 00:00:00', '1998-03-12 00:00:00', 1.0),
 ('BOTTM', '1998-03-25 00:00:00', '1998-03-13 00:00:00', 12.0),
 ('BOTTM', '1998-03-27 00:00:00', '1998-03-25 00:00:00', 2.0),
 ('BOTTM', '1998-04-16 00:00:00', '1998-03-27 00:00:00', 20.0),
 ('BOTTM', '1998-04-23 00:00:00', '1998-04-16 00:00:00', 7.0),
 ('BOTTM', '1998-04-24 00:00:00', '1998-04-23 00:00:00', 1.0),
 ('BSBEV', '1996-08-26 00:00:00', None, None),
 ('BSBEV', '1997-03-11 00:00:00', '1996-08-26 00:00:00', 197.0),
 ('BSBEV', '1997-03-24 00:00:00', '1997-03-11 00:00:00', 13.0),
 ('BSBEV', '1997-05-15 00:00:00', '1997-03-24 00:00:00', 52.0),
 ('BSBEV', '1997-05-16 00:00:00', '1997-05-15 00:00:00', 1.0),
 ('BSBEV', '1997-06-24 00:00:00', '1997-05-16 00:00:00', 39.0),
 ('BSBEV', '1997-07-15 00:00:00', '1997-06-24 00:00:00', 21.0),
 ('BSBEV', '1998-03-11 00:00:00', '1997-07-15 00:00:00', 239.0),
 ('BSBEV', '1998-03-13 00:00:00', '1998-03-11 00:00:00', 2.0),
 ('BSBEV', '1998-04-14 00:00:00', '1998-03-13 00:00:00', 32.0),
 ('CACTU', '1997-04-29 00:00:00', None, None),
 ('CACTU', '1997-12-17 00:00:00', '1997-04-29 00:00:00', 232.0),
 ('CACTU', '1998-01-07 00:00:00', '1997-12-17 00:00:00', 21.0),
 ('CACTU', '1998-02-11 00:00:00', '1998-01-07 00:00:00', 35.0),
 ('CACTU', '1998-03-10 00:00:00', '1998-02-11 00:00:00', 27.0),
 ('CACTU', '1998-04-28 00:00:00', '1998-03-10 00:00:00', 49.0),
 ('CENTC', '1996-07-18 00:00:00', None, None),
 ('CHOPS', '1996-07-11 00:00:00', None, None),
 ('CHOPS', '1996-12-03 00:00:00', '1996-07-11 00:00:00', 145.0),
 ('CHOPS', '1997-04-28 00:00:00', '1996-12-03 00:00:00', 146.0),
 ('CHOPS', '1997-11-06 00:00:00', '1997-04-28 00:00:00', 192.0),
 ('CHOPS', '1997-11-19 00:00:00', '1997-11-06 00:00:00', 13.0),
 ('CHOPS', '1998-03-20 00:00:00', '1997-11-19 00:00:00', 121.0),
 ('CHOPS', '1998-04-16 00:00:00', '1998-03-20 00:00:00', 27.0),
 ('CHOPS', '1998-04-22 00:00:00', '1998-04-16 00:00:00', 6.0),
 ('COMMI', '1996-08-27 00:00:00', None, None),
 ('COMMI', '1997-03-06 00:00:00', '1996-08-27 00:00:00', 191.0),
 ('COMMI', '1997-04-02 00:00:00', '1997-03-06 00:00:00', 27.0),
 ('COMMI', '1998-03-23 00:00:00', '1997-04-02 00:00:00', 355.0),
 ('COMMI', '1998-04-22 00:00:00', '1998-03-23 00:00:00', 30.0),
 ('CONSH', '1997-02-04 00:00:00', None, None),
 ('CONSH', '1997-03-03 00:00:00', '1997-02-04 00:00:00', 27.0),
 ('CONSH', '1998-01-23 00:00:00', '1997-03-03 00:00:00', 326.0),
 ('DRACD', '1996-11-26 00:00:00', None, None),
 ('DRACD', '1996-12-23 00:00:00', '1996-11-26 00:00:00', 27.0),
 ('DRACD', '1997-12-25 00:00:00', '1996-12-23 00:00:00', 367.0),
 ('DRACD', '1998-01-09 00:00:00', '1997-12-25 00:00:00', 15.0),
 ('DRACD', '1998-04-20 00:00:00', '1998-01-09 00:00:00', 101.0),
 ('DRACD', '1998-05-04 00:00:00', '1998-04-20 00:00:00', 14.0),
 ('DUMON', '1996-09-20 00:00:00', None, None),
 ('DUMON', '1997-07-24 00:00:00', '1996-09-20 00:00:00', 307.0),
 ('DUMON', '1997-09-26 00:00:00', '1997-07-24 00:00:00', 64.0),
 ('DUMON', '1998-02-16 00:00:00', '1997-09-26 00:00:00', 143.0),
 ('EASTC', '1996-11-26 00:00:00', None, None),
 ('EASTC', '1997-01-01 00:00:00', '1996-11-26 00:00:00', 36.0),
 ('EASTC', '1997-05-09 00:00:00', '1997-01-01 00:00:00', 128.0),
 ('EASTC', '1997-11-03 00:00:00', '1997-05-09 00:00:00', 178.0),
 ('EASTC', '1998-03-31 00:00:00', '1997-11-03 00:00:00', 148.0),
 ('EASTC', '1998-04-15 00:00:00', '1998-03-31 00:00:00', 15.0),
 ('EASTC', '1998-04-24 00:00:00', '1998-04-15 00:00:00', 9.0),
 ('EASTC', '1998-04-28 00:00:00', '1998-04-24 00:00:00', 4.0),
 ('ERNSH', '1996-07-17 00:00:00', None, None),
 ('ERNSH', '1996-07-23 00:00:00', '1996-07-17 00:00:00', 6.0),
 ('ERNSH', '1996-11-11 00:00:00', '1996-07-23 00:00:00', 111.0),
 ('ERNSH', '1996-11-29 00:00:00', '1996-11-11 00:00:00', 18.0),
 ('ERNSH', '1996-12-13 00:00:00', '1996-11-29 00:00:00', 14.0),
 ('ERNSH', '1996-12-23 00:00:00', '1996-12-13 00:00:00', 10.0),
 ('ERNSH', '1997-01-02 00:00:00', '1996-12-23 00:00:00', 10.0),
 ('ERNSH', '1997-01-03 00:00:00', '1997-01-02 00:00:00', 1.0),
 ('ERNSH', '1997-01-30 00:00:00', '1997-01-03 00:00:00', 27.0),
 ('ERNSH', '1997-02-11 00:00:00', '1997-01-30 00:00:00', 12.0),
 ('ERNSH', '1997-04-22 00:00:00', '1997-02-11 00:00:00', 70.0),
 ('ERNSH', '1997-06-17 00:00:00', '1997-04-22 00:00:00', 56.0),
 ('ERNSH', '1997-07-10 00:00:00', '1997-06-17 00:00:00', 23.0),
 ('ERNSH', '1997-08-15 00:00:00', '1997-07-10 00:00:00', 36.0),
 ('ERNSH', '1997-09-12 00:00:00', '1997-08-15 00:00:00', 28.0),
 ('ERNSH', '1997-10-09 00:00:00', '1997-09-12 00:00:00', 27.0),
 ('ERNSH', '1997-12-03 00:00:00', '1997-10-09 00:00:00', 55.0),
 ('ERNSH', '1997-12-10 00:00:00', '1997-12-03 00:00:00', 7.0),
 ('ERNSH', '1997-12-11 00:00:00', '1997-12-10 00:00:00', 1.0),
 ('ERNSH', '1997-12-15 00:00:00', '1997-12-11 00:00:00', 4.0),
 ('ERNSH', '1997-12-24 00:00:00', '1997-12-15 00:00:00', 9.0),
 ('ERNSH', '1998-01-16 00:00:00', '1997-12-24 00:00:00', 23.0),
 ('ERNSH', '1998-01-27 00:00:00', '1998-01-16 00:00:00', 11.0),
 ('ERNSH', '1998-02-18 00:00:00', '1998-01-27 00:00:00', 22.0),
 ('ERNSH', '1998-03-23 00:00:00', '1998-02-18 00:00:00', 33.0),
 ('ERNSH', '1998-03-26 00:00:00', '1998-03-23 00:00:00', 3.0),
 ('ERNSH', '1998-04-01 00:00:00', '1998-03-26 00:00:00', 6.0),
 ('ERNSH', '1998-04-08 00:00:00', '1998-04-01 00:00:00', 7.0),
 ('ERNSH', '1998-04-13 00:00:00', '1998-04-08 00:00:00', 5.0),
 ('ERNSH', '1998-05-05 00:00:00', '1998-04-13 00:00:00', 22.0),
 ('FAMIA', '1996-11-06 00:00:00', None, None),
 ('FAMIA', '1996-12-18 00:00:00', '1996-11-06 00:00:00', 42.0),
 ('FAMIA', '1997-01-14 00:00:00', '1996-12-18 00:00:00', 27.0),
 ('FAMIA', '1997-04-21 00:00:00', '1997-01-14 00:00:00', 97.0),
 ('FAMIA', '1997-06-26 00:00:00', '1997-04-21 00:00:00', 66.0),
 ('FAMIA', '1997-08-29 00:00:00', '1997-06-26 00:00:00', 64.0),
 ('FAMIA', '1997-10-31 00:00:00', '1997-08-29 00:00:00', 63.0),
 ('FOLIG', '1997-01-08 00:00:00', None, None),
 ('FOLIG', '1997-03-20 00:00:00', '1997-01-08 00:00:00', 71.0),
 ('FOLIG', '1997-08-15 00:00:00', '1997-03-20 00:00:00', 148.0),
 ('FOLIG', '1997-12-03 00:00:00', '1997-08-15 00:00:00', 110.0),
 ('FOLIG', '1997-12-22 00:00:00', '1997-12-03 00:00:00', 19.0),
 ('FOLKO', '1996-07-24 00:00:00', None, None),
 ('FOLKO', '1996-10-11 00:00:00', '1996-07-24 00:00:00', 79.0),
 ('FOLKO', '1996-12-10 00:00:00', '1996-10-11 00:00:00', 60.0),
 ('FOLKO', '1997-02-03 00:00:00', '1996-12-10 00:00:00', 55.0),
 ('FOLKO', '1997-02-28 00:00:00', '1997-02-03 00:00:00', 25.0),
 ('FOLKO', '1997-05-12 00:00:00', '1997-02-28 00:00:00', 73.0),
 ('FOLKO', '1997-06-06 00:00:00', '1997-05-12 00:00:00', 25.0),
 ('FOLKO', '1997-10-14 00:00:00', '1997-06-06 00:00:00', 130.0),
 ('FOLKO', '1997-12-02 00:00:00', '1997-10-14 00:00:00', 49.0),
 ('FOLKO', '1997-12-11 00:00:00', '1997-12-02 00:00:00', 9.0),
 ('FOLKO', '1998-01-09 00:00:00', '1997-12-11 00:00:00', 29.0),
 ('FOLKO', '1998-02-10 00:00:00', '1998-01-09 00:00:00', 32.0),
 ('FOLKO', '1998-02-23 00:00:00', '1998-02-10 00:00:00', 13.0),
 ('FOLKO', '1998-03-17 00:00:00', '1998-02-23 00:00:00', 22.0),
 ('FOLKO', '1998-03-26 00:00:00', '1998-03-17 00:00:00', 9.0),
 ('FOLKO', '1998-03-27 00:00:00', '1998-03-26 00:00:00', 1.0),
 ('FOLKO', '1998-04-01 00:00:00', '1998-03-27 00:00:00', 5.0),
 ('FOLKO', '1998-04-06 00:00:00', '1998-04-01 00:00:00', 5.0),
 ('FOLKO', '1998-04-27 00:00:00', '1998-04-06 00:00:00', 21.0),
 ('FRANK', '1996-07-29 00:00:00', None, None),
 ('FRANK', '1996-10-24 00:00:00', '1996-07-29 00:00:00', 87.0),
 ('FRANK', '1996-10-30 00:00:00', '1996-10-24 00:00:00', 6.0),
 ('FRANK', '1996-12-27 00:00:00', '1996-10-30 00:00:00', 58.0),
 ('FRANK', '1997-03-27 00:00:00', '1996-12-27 00:00:00', 90.0),
 ('FRANK', '1997-06-06 00:00:00', '1997-03-27 00:00:00', 71.0),
 ('FRANK', '1997-08-07 00:00:00', '1997-06-06 00:00:00', 62.0),
 ('FRANK', '1997-09-02 00:00:00', '1997-08-07 00:00:00', 26.0),
 ('FRANK', '1997-09-16 00:00:00', '1997-09-02 00:00:00', 14.0),
 ('FRANK', '1997-09-19 00:00:00', '1997-09-16 00:00:00', 3.0),
 ('FRANK', '1997-10-24 00:00:00', '1997-09-19 00:00:00', 35.0),
 ('FRANK', '1997-12-23 00:00:00', '1997-10-24 00:00:00', 60.0),
 ('FRANK', '1998-01-29 00:00:00', '1997-12-23 00:00:00', 37.0),
 ('FRANK', '1998-03-05 00:00:00', '1998-01-29 00:00:00', 35.0),
 ('FRANK', '1998-04-09 00:00:00', '1998-03-05 00:00:00', 35.0),
 ('FRANR', '1997-09-17 00:00:00', None, None),
 ('FRANR', '1998-01-29 00:00:00', '1997-09-17 00:00:00', 134.0),
 ('FRANR', '1998-03-24 00:00:00', '1998-01-29 00:00:00', 54.0),
 ('FRANS', '1997-01-22 00:00:00', None, None),
 ('FRANS', '1997-10-20 00:00:00', '1997-01-22 00:00:00', 271.0),
 ('FRANS', '1997-11-25 00:00:00', '1997-10-20 00:00:00', 36.0),
 ('FRANS', '1997-12-31 00:00:00', '1997-11-25 00:00:00', 36.0),
 ('FRANS', '1998-04-15 00:00:00', '1997-12-31 00:00:00', 105.0),
 ('FRANS', '1998-04-30 00:00:00', '1998-04-15 00:00:00', 15.0),
 ('FURIB', '1996-10-14 00:00:00', None, None),
 ('FURIB', '1996-11-12 00:00:00', '1996-10-14 00:00:00', 29.0),
 ('FURIB', '1997-03-04 00:00:00', '1996-11-12 00:00:00', 112.0),
 ('FURIB', '1997-03-31 00:00:00', '1997-03-04 00:00:00', 27.0),
 ('FURIB', '1997-05-28 00:00:00', '1997-03-31 00:00:00', 58.0),
 ('FURIB', '1997-07-18 00:00:00', '1997-05-28 00:00:00', 51.0),
 ('FURIB', '1997-09-10 00:00:00', '1997-07-18 00:00:00', 54.0),
 ('FURIB', '1998-03-19 00:00:00', '1997-09-10 00:00:00', 190.0),
 ('GALED', '1996-11-28 00:00:00', None, None),
 ('GALED', '1997-01-27 00:00:00', '1996-11-28 00:00:00', 60.0),
 ('GALED', '1997-06-13 00:00:00', '1997-01-27 00:00:00', 137.0),
 ('GALED', '1998-02-13 00:00:00', '1997-06-13 00:00:00', 245.0),
 ('GALED', '1998-03-05 00:00:00', '1998-02-13 00:00:00', 20.0),
 ('GODOS', '1996-09-11 00:00:00', None, None),
 ('GODOS', '1997-05-28 00:00:00', '1996-09-11 00:00:00', 259.0),
 ('GODOS', '1997-08-12 00:00:00', '1997-05-28 00:00:00', 76.0),
 ('GODOS', '1998-02-05 00:00:00', '1997-08-12 00:00:00', 177.0),
 ('GODOS', '1998-02-06 00:00:00', '1998-02-05 00:00:00', 1.0),
 ('GODOS', '1998-02-16 00:00:00', '1998-02-06 00:00:00', 10.0),
 ('GODOS', '1998-02-26 00:00:00', '1998-02-16 00:00:00', 10.0),
 ('GODOS', '1998-03-13 00:00:00', '1998-02-26 00:00:00', 15.0),
 ('GODOS', '1998-04-08 00:00:00', '1998-03-13 00:00:00', 26.0),
 ('GODOS', '1998-04-21 00:00:00', '1998-04-08 00:00:00', 13.0),
 ('GOURL', '1997-01-23 00:00:00', None, None),
 ('GOURL', '1997-09-01 00:00:00', '1997-01-23 00:00:00', 221.0),
 ('GOURL', '1997-09-29 00:00:00', '1997-09-01 00:00:00', 28.0),
 ('GOURL', '1997-10-17 00:00:00', '1997-09-29 00:00:00', 18.0),
 ('GOURL', '1997-11-07 00:00:00', '1997-10-17 00:00:00', 21.0),
 ('GOURL', '1997-12-15 00:00:00', '1997-11-07 00:00:00', 38.0),
 ('GOURL', '1997-12-22 00:00:00', '1997-12-15 00:00:00', 7.0),
 ('GOURL', '1998-03-18 00:00:00', '1997-12-22 00:00:00', 86.0),
 ('GOURL', '1998-04-24 00:00:00', '1998-03-18 00:00:00', 37.0),
 ('GREAL', '1997-05-06 00:00:00', None, None),
 ('GREAL', '1997-07-04 00:00:00', '1997-05-06 00:00:00', 59.0),
 ('GREAL', '1997-07-31 00:00:00', '1997-07-04 00:00:00', 27.0),
 ('GREAL', '1997-07-31 00:00:00', '1997-07-31 00:00:00', 0.0),
 ('GREAL', '1997-09-04 00:00:00', '1997-07-31 00:00:00', 35.0),
 ('GREAL', '1997-09-25 00:00:00', '1997-09-04 00:00:00', 21.0),
 ('GREAL', '1998-01-06 00:00:00', '1997-09-25 00:00:00', 103.0),
 ('GREAL', '1998-03-09 00:00:00', '1998-01-06 00:00:00', 62.0),
 ('GREAL', '1998-04-07 00:00:00', '1998-03-09 00:00:00', 29.0),
 ('GREAL', '1998-04-22 00:00:00', '1998-04-07 00:00:00', 15.0),
 ('GREAL', '1998-04-30 00:00:00', '1998-04-22 00:00:00', 8.0),
 ('GROSR', '1996-07-30 00:00:00', None, None),
 ('GROSR', '1997-12-18 00:00:00', '1996-07-30 00:00:00', 506.0),
 ('HANAR', '1996-07-08 00:00:00', None, None),
 ('HANAR', '1996-07-10 00:00:00', '1996-07-08 00:00:00', 2.0),
 ('HANAR', '1997-05-19 00:00:00', '1996-07-10 00:00:00', 313.0),
 ('HANAR', '1997-08-26 00:00:00', '1997-05-19 00:00:00', 99.0),
 ('HANAR', '1997-10-02 00:00:00', '1997-08-26 00:00:00', 37.0),
 ('HANAR', '1997-12-09 00:00:00', '1997-10-02 00:00:00', 68.0),
 ('HANAR', '1997-12-18 00:00:00', '1997-12-09 00:00:00', 9.0),
 ('HANAR', '1998-02-13 00:00:00', '1997-12-18 00:00:00', 57.0),
 ('HANAR', '1998-02-24 00:00:00', '1998-02-13 00:00:00', 11.0),
 ('HANAR', '1998-03-03 00:00:00', '1998-02-24 00:00:00', 7.0),
 ('HANAR', '1998-03-04 00:00:00', '1998-03-03 00:00:00', 1.0),
 ('HANAR', '1998-03-27 00:00:00', '1998-03-04 00:00:00', 23.0),
 ('HANAR', '1998-04-14 00:00:00', '1998-03-27 00:00:00', 18.0),
 ('HANAR', '1998-04-27 00:00:00', '1998-04-14 00:00:00', 13.0),
 ('HILAA', '1996-07-16 00:00:00', None, None),
 ('HILAA', '1996-12-26 00:00:00', '1996-07-16 00:00:00', 163.0),
 ('HILAA', '1997-03-17 00:00:00', '1996-12-26 00:00:00', 81.0),
 ('HILAA', '1997-03-26 00:00:00', '1997-03-17 00:00:00', 9.0),
 ('HILAA', '1997-03-31 00:00:00', '1997-03-26 00:00:00', 5.0),
 ('HILAA', '1997-04-07 00:00:00', '1997-03-31 00:00:00', 7.0),
 ('HILAA', '1997-05-29 00:00:00', '1997-04-07 00:00:00', 52.0),
 ('HILAA', '1997-07-16 00:00:00', '1997-05-29 00:00:00', 48.0),
 ('HILAA', '1997-07-29 00:00:00', '1997-07-16 00:00:00', 13.0),
 ('HILAA', '1997-08-22 00:00:00', '1997-07-29 00:00:00', 24.0),
 ('HILAA', '1997-10-15 00:00:00', '1997-08-22 00:00:00', 54.0),
 ('HILAA', '1997-12-25 00:00:00', '1997-10-15 00:00:00', 71.0),
 ('HILAA', '1998-02-02 00:00:00', '1997-12-25 00:00:00', 39.0),
 ('HILAA', '1998-02-23 00:00:00', '1998-02-02 00:00:00', 21.0),
 ('HILAA', '1998-03-18 00:00:00', '1998-02-23 00:00:00', 23.0),
 ('HILAA', '1998-03-19 00:00:00', '1998-03-18 00:00:00', 1.0),
 ('HILAA', '1998-03-25 00:00:00', '1998-03-19 00:00:00', 6.0),
 ('HILAA', '1998-04-28 00:00:00', '1998-03-25 00:00:00', 34.0),
 ('HUNGC', '1996-12-06 00:00:00', None, None),
 ('HUNGC', '1996-12-25 00:00:00', '1996-12-06 00:00:00', 19.0),
 ('HUNGC', '1997-01-15 00:00:00', '1996-12-25 00:00:00', 21.0),
 ('HUNGC', '1997-07-16 00:00:00', '1997-01-15 00:00:00', 182.0),
 ('HUNGC', '1997-09-08 00:00:00', '1997-07-16 00:00:00', 54.0),
 ('HUNGO', '1996-09-05 00:00:00', None, None),
 ('HUNGO', '1996-09-19 00:00:00', '1996-09-05 00:00:00', 14.0),
 ('HUNGO', '1996-10-22 00:00:00', '1996-09-19 00:00:00', 33.0),
 ('HUNGO', '1996-12-05 00:00:00', '1996-10-22 00:00:00', 44.0),

The `LAG()` window function is used twice here, once to get the previous order date for each customer, and again to calculate the difference between the current order date and the previous order date. The `PARTITION BY` clause is used to separate the data into partitions based on the `CustomerID`. 

Since the `TIMESTAMPDIFF()` function in MySQL is not available in SQLite, we use the `julianday()` function to convert the dates to a floating point number, which we can then use for subtraction to find the difference between two dates.

### Exercise 4

In [ ]:
%%sql

SELECT 
    OrderID, 
    ProductID, 
    Quantity,
    AVG(Quantity) OVER (PARTITION BY ProductID ORDER BY OrderID ROWS BETWEEN 2 PRECEDING AND 0 FOLLOWING) as MovingAvgQuantity
FROM 
    OrderDetails
ORDER BY 
    ProductID, 
    OrderID;

The `AVG()` window function is used here to calculate the moving average of `Quantity` for the last 3 orders (the current order and the two preceding orders) for each product. The window is defined using the `PARTITION BY` clause (to segment the data by `ProductID`) and the `ORDER BY` clause (to arrange the data in order of `OrderID`). The `ROWS BETWEEN` clause specifies the size and location of the window – in this case, **the current row and the two rows preceding it.**

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/ExploreAI_logos/EAI_Blue_Dark.png"  style="width:200px";/>
</div>